O QUE EXISTE NESSA BASE DE DADOS?

In [1]:
from pathlib import Path

RAW_DIR = Path("../data/raw")

arquivos = sorted(RAW_DIR.glob("*.csv"))

for arquivo in arquivos:
    print(arquivo.name)

olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_orders_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv

In [2]:
import pandas as pd

tabelas = {}

for arquivo in arquivos:
    df = pd.read_csv(arquivo)
    tabelas[arquivo.stem] = df

In [3]:
print(f"Quantidade de tabelas carregadas: {len(tabelas)}")

for nome, df in tabelas.items():
    print(f"{nome}: {df.shape}")

Quantidade de tabelas carregadas: 9
olist_customers_dataset: (99441, 5)
olist_geolocation_dataset: (1000163, 5)
olist_order_items_dataset: (112650, 7)
olist_order_payments_dataset: (103886, 5)
olist_order_reviews_dataset: (99224, 7)
olist_orders_dataset: (99441, 8)
olist_products_dataset: (32951, 9)
olist_sellers_dataset: (3095, 4)
product_category_name_translation: (71, 2)

In [4]:
# Seleciona a tabela de clientes
df_customers = tabelas["olist_customers_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_customers_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_customers.shape[0]}")
print(f"Quantidade de colunas: {df_customers.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_customers.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_customers_dataset
======================================================================
Quantidade de linhas: 99441
Quantidade de colunas: 5

Colunas da tabela:
1. customer_id
2. customer_unique_id
3. customer_zip_code_prefix
4. customer_city
5. customer_state

In [5]:
# Seleciona a tabela de geolocalização
df_geolocation = tabelas["olist_geolocation_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_geolocation_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_geolocation.shape[0]}")
print(f"Quantidade de colunas: {df_geolocation.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_geolocation.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_geolocation_dataset
======================================================================
Quantidade de linhas: 1000163
Quantidade de colunas: 5

Colunas da tabela:
1. geolocation_zip_code_prefix
2. geolocation_lat
3. geolocation_lng
4. geolocation_city
5. geolocation_state

In [6]:
# Seleciona a tabela de itens dos pedidos
df_order_items = tabelas["olist_order_items_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_order_items_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_order_items.shape[0]}")
print(f"Quantidade de colunas: {df_order_items.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_order_items.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_order_items_dataset
======================================================================
Quantidade de linhas: 112650
Quantidade de colunas: 7

Colunas da tabela:
1. order_id
2. order_item_id
3. product_id
4. seller_id
5. shipping_limit_date
6. price
7. freight_value

In [7]:
# Seleciona a tabela de pagamentos dos pedidos
df_order_payments = tabelas["olist_order_payments_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_order_payments_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_order_payments.shape[0]}")
print(f"Quantidade de colunas: {df_order_payments.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_order_payments.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_order_payments_dataset
======================================================================
Quantidade de linhas: 103886
Quantidade de colunas: 5

Colunas da tabela:
1. order_id
2. payment_sequential
3. payment_type
4. payment_installments
5. payment_value

In [8]:
# Seleciona a tabela de avaliações dos pedidos
df_order_reviews = tabelas["olist_order_reviews_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_order_reviews_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_order_reviews.shape[0]}")
print(f"Quantidade de colunas: {df_order_reviews.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_order_reviews.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_order_reviews_dataset
======================================================================
Quantidade de linhas: 99224
Quantidade de colunas: 7

Colunas da tabela:
1. review_id
2. order_id
3. review_score
4. review_comment_title
5. review_comment_message
6. review_creation_date
7. review_answer_timestamp

In [9]:
# Seleciona a tabela de pedidos
df_orders = tabelas["olist_orders_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_orders_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_orders.shape[0]}")
print(f"Quantidade de colunas: {df_orders.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_orders.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_orders_dataset
======================================================================
Quantidade de linhas: 99441
Quantidade de colunas: 8

Colunas da tabela:
1. order_id
2. customer_id
3. order_status
4. order_purchase_timestamp
5. order_approved_at
6. order_delivered_carrier_date
7. order_delivered_customer_date
8. order_estimated_delivery_date

In [10]:
# Seleciona a tabela de produtos
df_products = tabelas["olist_products_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_products_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_products.shape[0]}")
print(f"Quantidade de colunas: {df_products.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_products.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_products_dataset
======================================================================
Quantidade de linhas: 32951
Quantidade de colunas: 9

Colunas da tabela:
1. product_id
2. product_category_name
3. product_name_lenght
4. product_description_lenght
5. product_photos_qty
6. product_weight_g
7. product_length_cm
8. product_height_cm
9. product_width_cm

In [11]:
# Seleciona a tabela de vendedores
df_sellers = tabelas["olist_sellers_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_sellers_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_sellers.shape[0]}")
print(f"Quantidade de colunas: {df_sellers.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_sellers.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_sellers_dataset
======================================================================
Quantidade de linhas: 3095
Quantidade de colunas: 4

Colunas da tabela:
1. seller_id
2. seller_zip_code_prefix
3. seller_city
4. seller_state

In [12]:
# Seleciona a tabela de tradução das categorias
df_category_translation = tabelas["product_category_name_translation"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: product_category_name_translation")
print("=" * 70)

print(f"Quantidade de linhas: {df_category_translation.shape[0]}")
print(f"Quantidade de colunas: {df_category_translation.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_category_translation.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: product_category_name_translation
======================================================================
Quantidade de linhas: 71
Quantidade de colunas: 2

Colunas da tabela:
1. product_category_name
2. product_category_name_english

## Data Discovery — orders

### Objetivo

Validar a granularidade da tabela `olist_orders_dataset` e investigar a unicidade de `order_id`.

### Hipótese inicial

- Uma linha representa um pedido.
- `order_id` funciona como identificador do pedido.

In [13]:
df_orders = tabelas["olist_orders_dataset"]

print("Tabela:", "olist_orders_dataset")
print("Linhas:", df_orders.shape[0])
print("Colunas:", df_orders.shape[1])

print("\nQuantidade de order_id únicos:", df_orders["order_id"].nunique())

print("Quantidade de order_id nulos:", df_orders["order_id"].isna().sum())

print("Quantidade total de linhas:", len(df_orders))

Tabela: olist_orders_dataset
Linhas: 99441
Colunas: 8

Quantidade de order_id únicos: 99441
Quantidade de order_id nulos: 0
Quantidade total de linhas: 99441

In [14]:
print("Colunas da tabela orders:\n")

for numero, coluna in enumerate(df_orders.columns, start=1):
    print(f"{numero}. {coluna}")

Colunas da tabela orders:

1. order_id
2. customer_id
3. order_status
4. order_purchase_timestamp
5. order_approved_at
6. order_delivered_carrier_date
7. order_delivered_customer_date
8. order_estimated_delivery_date

In [15]:
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [16]:
df_customers = tabelas["olist_customers_dataset"]

print("Linhas em customers:", len(df_customers))
print("customer_id únicos:", df_customers["customer_id"].nunique())
print("customer_id nulos:", df_customers["customer_id"].isna().sum())

Linhas em customers: 99441
customer_id únicos: 99441
customer_id nulos: 0

In [17]:
customer_ids_orders = df_orders["customer_id"]

print("Clientes distintos em orders:", customer_ids_orders.nunique())
print("Clientes nulos em orders:", customer_ids_orders.isna().sum())

Clientes distintos em orders: 99441
Clientes nulos em orders: 0

In [18]:
customer_ids_orders = set(df_orders["customer_id"])
customer_ids_customers = set(df_customers["customer_id"])

clientes_orders_sem_cadastro = customer_ids_orders - customer_ids_customers

print(
    "customer_id de orders sem correspondência em customers:",
    len(clientes_orders_sem_cadastro)
)

customer_id de orders sem correspondência em customers: 0

In [19]:
clientes_customers_sem_pedido = (
    customer_ids_customers - customer_ids_orders
)

print(
    "customer_id de customers sem correspondência em orders:",
    len(clientes_customers_sem_pedido)
)

customer_id de customers sem correspondência em orders: 0

In [20]:
customer_orders_frequency = df_orders["customer_id"].value_counts()

print("Distribuição da quantidade de pedidos por customer_id:")
print(customer_orders_frequency.value_counts().sort_index())

print(
    "\nMaior número de pedidos associado a um único customer_id:",
    customer_orders_frequency.max()
)

Distribuição da quantidade de pedidos por customer_id:
count
1    99441
Name: count, dtype: int64

Maior número de pedidos associado a um único customer_id: 1

In [21]:
print(
    "customer_unique_id únicos:",
    df_customers["customer_unique_id"].nunique()
)

print(
    "customer_unique_id nulos:",
    df_customers["customer_unique_id"].isna().sum()
)

customer_unique_id únicos: 96096
customer_unique_id nulos: 0

In [22]:
unique_customer_frequency = df_customers["customer_unique_id"].value_counts()

print(
    "Clientes com mais de um customer_id:",
    (unique_customer_frequency > 1).sum()
)

print(
    "Maior quantidade de customer_id para um único customer_unique_id:",
    unique_customer_frequency.max()
)

Clientes com mais de um customer_id: 2997
Maior quantidade de customer_id para um único customer_unique_id: 17

In [23]:
print("Estados distintos:", df_customers["customer_state"].nunique())
print("Cidades distintas:", df_customers["customer_city"].nunique())
print("CEPs distintos:", df_customers["customer_zip_code_prefix"].nunique())

Estados distintos: 27
Cidades distintas: 4119
CEPs distintos: 14994

In [24]:
df_items = tabelas["olist_order_items_dataset"]

print("Tabela:", "olist_order_items_dataset")
print("Linhas:", df_items.shape[0])
print("Colunas:", df_items.shape[1])

print(
    "\nQuantidade de order_id únicos:",
    df_items["order_id"].nunique()
)

print(
    "Quantidade de order_id nulos:",
    df_items["order_id"].isna().sum()
)

Tabela: olist_order_items_dataset
Linhas: 112650
Colunas: 7

Quantidade de order_id únicos: 98666
Quantidade de order_id nulos: 0

In [25]:
print(
    "order_item_id únicos:",
    df_items["order_item_id"].nunique()
)

print(
    "order_item_id nulos:",
    df_items["order_item_id"].isna().sum()
)

print(
    "Duplicidades em (order_id, order_item_id):",
    df_items[["order_id", "order_item_id"]].duplicated().sum()
)

order_item_id únicos: 21
order_item_id nulos: 0
Duplicidades em (order_id, order_item_id): 0

In [26]:
order_ids_orders = set(df_orders["order_id"])
order_ids_items = set(df_items["order_id"])

print(
    "order_id em order_items sem correspondência em orders:",
    len(order_ids_items - order_ids_orders)
)

print(
    "order_id em orders sem correspondência em order_items:",
    len(order_ids_orders - order_ids_items)
)

order_id em order_items sem correspondência em orders: 0
order_id em orders sem correspondência em order_items: 775

In [27]:
orders_sem_itens = df_orders[
    ~df_orders["order_id"].isin(df_items["order_id"])
]

print(
    "Quantidade de pedidos sem itens:",
    len(orders_sem_itens)
)

print("\nDistribuição por status:")
print(
    orders_sem_itens["order_status"]
    .value_counts()
)

Quantidade de pedidos sem itens: 775

Distribuição por status:
order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [28]:
print("Nulos por coluna:")

print(
    df_items[
        [
            "product_id",
            "seller_id",
            "shipping_limit_date",
            "price",
            "freight_value"
        ]
    ].isna().sum()
)

Nulos por coluna:
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [29]:
df_products = tabelas["olist_products_dataset"]

product_ids_items = set(df_items["product_id"])
product_ids_products = set(df_products["product_id"])

print(
    "product_id em order_items sem correspondência em products:",
    len(product_ids_items - product_ids_products)
)

print(
    "product_id em products sem ocorrência em order_items:",
    len(product_ids_products - product_ids_items)
)

product_id em order_items sem correspondência em products: 0
product_id em products sem ocorrência em order_items: 0

In [30]:
df_sellers = tabelas["olist_sellers_dataset"]

print("Linhas em sellers:", len(df_sellers))
print(
    "seller_id únicos:",
    df_sellers["seller_id"].nunique()
)
print(
    "seller_id nulos:",
    df_sellers["seller_id"].isna().sum()
)

Linhas em sellers: 3095
seller_id únicos: 3095
seller_id nulos: 0

In [31]:
seller_ids_items = set(df_items["seller_id"])
seller_ids_sellers = set(df_sellers["seller_id"])

print(
    "seller_id em order_items sem correspondência em sellers:",
    len(seller_ids_items - seller_ids_sellers)
)

print(
    "seller_id em sellers sem ocorrência em order_items:",
    len(seller_ids_sellers - seller_ids_items)
)

seller_id em order_items sem correspondência em sellers: 0
seller_id em sellers sem ocorrência em order_items: 0

In [32]:
df_payments = tabelas["olist_order_payments_dataset"]

print("Tabela:", "olist_order_payments_dataset")
print("Linhas:", df_payments.shape[0])
print("Colunas:", df_payments.shape[1])

print(
    "\nQuantidade de order_id únicos:",
    df_payments["order_id"].nunique()
)

print(
    "Quantidade de order_id nulos:",
    df_payments["order_id"].isna().sum()
)

Tabela: olist_order_payments_dataset
Linhas: 103886
Colunas: 5

Quantidade de order_id únicos: 99440
Quantidade de order_id nulos: 0

In [33]:
payment_frequency = df_payments["order_id"].value_counts()

print(
    "Pedidos com mais de um registro de pagamento:",
    (payment_frequency > 1).sum()
)

print(
    "Maior quantidade de registros de pagamento para um pedido:",
    payment_frequency.max()
)

Pedidos com mais de um registro de pagamento: 2961
Maior quantidade de registros de pagamento para um pedido: 29

In [34]:
print(
    "payment_sequential únicos:",
    df_payments["payment_sequential"].nunique()
)

print(
    "payment_sequential nulos:",
    df_payments["payment_sequential"].isna().sum()
)

print(
    "\nDistribuição dos valores de payment_sequential:"
)

print(
    df_payments["payment_sequential"]
    .value_counts()
    .sort_index()
)

payment_sequential únicos: 29
payment_sequential nulos: 0

Distribuição dos valores de payment_sequential:
payment_sequential
1     99360
2      3039
3       581
4       278
5       170
6       118
7        82
8        54
9        43
10       34
11       29
12       21
13       13
14       10
15        8
16        6
17        6
18        6
19        6
20        4
21        4
22        3
23        2
24        2
25        2
26        2
27        1
28        1
29        1
Name: count, dtype: int64

In [35]:
order_ids_payments = set(df_payments["order_id"])
order_ids_orders = set(df_orders["order_id"])

print(
    "order_id em order_payments sem correspondência em orders:",
    len(order_ids_payments - order_ids_orders)
)

print(
    "order_id em orders sem ocorrência em order_payments:",
    len(order_ids_orders - order_ids_payments)
)

order_id em order_payments sem correspondência em orders: 0
order_id em orders sem ocorrência em order_payments: 1

In [36]:
order_ids_payments = set(df_payments["order_id"])
order_ids_orders = set(df_orders["order_id"])

orders_sem_pagamento = order_ids_orders - order_ids_payments

print("Quantidade de pedidos sem pagamento:", len(orders_sem_pagamento))
print("Pedido(s):", orders_sem_pagamento)

Quantidade de pedidos sem pagamento: 1
Pedido(s): {'bfbd0f9bdef84302105ad712db648a6c'}

In [37]:
df_orders[
    df_orders["order_id"] == "bfbd0f9bdef84302105ad712db648a6c"
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
30710,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00

In [38]:
df_items[
    df_items["order_id"] == "bfbd0f9bdef84302105ad712db648a6c"
]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
84389,bfbd0f9bdef84302105ad712db648a6c,1,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83
84390,bfbd0f9bdef84302105ad712db648a6c,2,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83
84391,bfbd0f9bdef84302105ad712db648a6c,3,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83

In [39]:
df_reviews = tabelas["olist_order_reviews_dataset"]

In [40]:
print("Linhas:", len(df_reviews))
print("Colunas:", df_reviews.shape[1])
print("Colunas:", df_reviews.columns.tolist())

Linhas: 99224
Colunas: 7
Colunas: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

In [41]:
df_reviews[
    df_reviews["order_id"] == "bfbd0f9bdef84302105ad712db648a6c"
]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
37547,6916ca4502d6d3bfd39818759d55d536,bfbd0f9bdef84302105ad712db648a6c,1,NaN,nao recebi o produto e nem resposta da empresa,2016-10-06 00:00:00,2016-10-07 18:32:28

In [42]:
df_payments["payment_type"].value_counts(dropna=False)

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [43]:
df_payments[
    df_payments["payment_type"] == "not_defined"
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0

In [44]:
df_payments["payment_installments"].value_counts().sort_index()

payment_installments
0         2
1     52546
2     12413
3     10461
4      7098
5      5239
6      3920
7      1626
8      4268
9       644
10     5328
11       23
12      133
13       16
14       15
15       74
16        5
17        8
18       27
20       17
21        3
22        1
23        1
24       18
Name: count, dtype: int64

In [45]:
df_payments[
    df_payments["payment_installments"] == 0
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [46]:
df_payments[
    df_payments["order_id"].isin([
        "744bade1fcf9ff3f31d860ace076d422",
        "1a57108394169c0b47d8f876acc9ba2d"
    ])
].sort_values(["order_id", "payment_sequential"])

,order_id,payment_sequential,payment_type,payment_installments,payment_value
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69

In [47]:
df_orders[
    df_orders["order_id"].isin([
        "744bade1fcf9ff3f31d860ace076d422",
        "1a57108394169c0b47d8f876acc9ba2d"
    ])
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
63782,744bade1fcf9ff3f31d860ace076d422,5e5794daaa13f73e2f1cdb4114529843,delivered,2018-04-22 11:34:42,2018-04-24 19:04:46,2018-04-24 03:14:34,2018-04-27 20:55:28,2018-05-16 00:00:00
66368,1a57108394169c0b47d8f876acc9ba2d,48ebb06cf56dba9d009230cc751bb195,delivered,2018-05-15 16:25:14,2018-05-15 16:36:52,2018-05-17 12:37:00,2018-05-24 15:45:41,2018-06-06 00:00:00

In [48]:
df_items[
    df_items["order_id"].isin([
        "744bade1fcf9ff3f31d860ace076d422",
        "1a57108394169c0b47d8f876acc9ba2d"
    ])
].sort_values(["order_id", "order_item_id"])

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
11589,1a57108394169c0b47d8f876acc9ba2d,1,db35a562fb6ba63e19fa42a15349dc04,282f23a9769b2690c5dda22e316f9941,2018-05-18 16:31:54,41.69,23.28
11590,1a57108394169c0b47d8f876acc9ba2d,2,db35a562fb6ba63e19fa42a15349dc04,282f23a9769b2690c5dda22e316f9941,2018-05-18 16:31:54,41.69,23.28
51167,744bade1fcf9ff3f31d860ace076d422,1,0cf573090c66bb30ac5e53c82bdb0403,7202e2ba20579a9bd1acb29e61fe71f6,2018-04-26 12:31:06,45.90,12.79

In [49]:
totais_items = (
    df_items
    .groupby("order_id")
    .agg(
        valor_produtos=("price", "sum"),
        valor_frete=("freight_value", "sum")
    )
    .reset_index()
)

totais_items["valor_itens_frete"] = (
    totais_items["valor_produtos"] +
    totais_items["valor_frete"]
)

totais_items.head()

,order_id,valor_produtos,valor_frete,valor_itens_frete
0,00010242fe8c5a6d1ba2dd792cb16214,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,12.99,12.79,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,199.90,18.14,218.04

In [50]:
totais_payments = (
    df_payments
    .groupby("order_id")
    .agg(
        valor_pagamentos=("payment_value", "sum")
    )
    .reset_index()
)

totais_payments.head()

                           order_id  valor_pagamentos
0  00010242fe8c5a6d1ba2dd792cb16214             72.19
1  00018f77f2f0320c557190d7a144bdd3            259.83
2  000229ec398224ef6ca0657da4fc703e            216.87
3  00024acbcdf0a6daa1e931b038114c75             25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9            218.04

In [51]:
comparacao_valores = totais_items.merge(
    totais_payments,
    on="order_id",
    how="inner"
)

comparacao_valores.head()

,order_id,valor_produtos,valor_frete,valor_itens_frete,valor_pagamentos
0,00010242fe8c5a6d1ba2dd792cb16214,58.90,13.29,72.19,72.19
1,00018f77f2f0320c557190d7a144bdd3,239.90,19.93,259.83,259.83
2,000229ec398224ef6ca0657da4fc703e,199.00,17.87,216.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,12.99,12.79,25.78,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,199.90,18.14,218.04,218.04

In [52]:
comparacao_valores["diferenca"] = (
    comparacao_valores["valor_pagamentos"]
    - comparacao_valores["valor_itens_frete"]
)

comparacao_valores["diferenca"].describe()

count    98665.000000
mean         0.029092
std          1.129221
min        -51.620000
25%          0.000000
50%          0.000000
75%          0.000000
max        182.810000
Name: diferenca, dtype: float64

In [53]:
import numpy as np

comparacao_valores["corresponde"] = np.isclose(
    comparacao_valores["valor_pagamentos"],
    comparacao_valores["valor_itens_frete"],
    atol=0.01
)

comparacao_valores["corresponde"].value_counts()

corresponde
True     98365
False      300
Name: count, dtype: int64

In [54]:
divergencias = (
    comparacao_valores[
        ~comparacao_valores["corresponde"]
    ]
    .copy()
    .sort_values("diferenca")
)

divergencias[
    [
        "order_id",
        "valor_produtos",
        "valor_frete",
        "valor_itens_frete",
        "valor_pagamentos",
        "diferenca"
    ]
].head(10)

,order_id,valor_produtos,valor_frete,valor_itens_frete,valor_pagamentos,diferenca
14628,262118ce178bb3e4590a3adcf6d62e6b,119.80,57.94,177.74,126.12,-51.62
97605,fd33085945f15975375cd8ec85440511,217.99,16.63,234.62,212.82,-21.80
42504,6e57e23ecac1ae881286657694444267,330.00,20.41,350.41,333.91,-16.50
25102,4154bf1348caac78152fe76e3e9c4af8,149.90,15.36,165.26,150.27,-14.99
42292,6dcf0aeb8b1eb4021c26e1d0e9394979,299.00,34.92,333.92,318.97,-14.95
5533,0e556f5eafbf3eb399290101b183b10e,49.80,45.86,95.66,81.90,-13.76
49461,8092da256aefda13b330290d2ca86521,103.90,11.75,115.65,105.26,-10.39
65449,aa6bd33ba1853d846d3085a88ae37083,19.90,15.24,35.14,25.14,-10.00
25960,4387477eec4b3c89b39f3f454940d059,198.00,33.92,231.92,222.02,-9.90
76694,c6f6cbb3c845593222d5c594bb69c5fd,89.90,23.43,113.33,104.34,-8.99

In [55]:
pedido_teste = "262118ce178bb3e4590a3adcf6d62e6b"

print("=== PEDIDO ===")
print(
    df_orders[
        df_orders["order_id"] == pedido_teste
    ]
)

print("\n=== ITENS ===")
print(
    df_items[
        df_items["order_id"] == pedido_teste
    ]
)

print("\n=== PAGAMENTOS ===")
print(
    df_payments[
        df_payments["order_id"] == pedido_teste
    ]
)

=== PEDIDO ===
                               order_id                       customer_id  \
31661  262118ce178bb3e4590a3adcf6d62e6b  2a69da30b726b7f3db7f1059af5d4304

      order_status order_purchase_timestamp    order_approved_at  \
31661    delivered      2016-10-06 14:59:56  2016-10-07 12:13:49

      order_delivered_carrier_date order_delivered_customer_date  \
31661          2016-11-17 08:27:59           2016-11-17 16:23:46

      order_estimated_delivery_date
31661           2016-11-30 00:00:00

=== ITENS ===
                               order_id  order_item_id  \
16662  262118ce178bb3e4590a3adcf6d62e6b              1
16663  262118ce178bb3e4590a3adcf6d62e6b              2

                             product_id                         seller_id  \
16662  6aeed495dcb87dd06532f70dea6ebb5a  b56906f7fd1696e043f1bcce164c487b
16663  6aeed495dcb87dd06532f70dea6ebb5a  b56906f7fd1696e043f1bcce164c487b

       shipping_limit_date  price  freight_value
16662  2016-10-11 12:13:50   59.9          28.97
16663  2016-10-11 12:13:50   59.9          28.97

=== PAGAMENTOS ===
                               order_id  payment_sequential payment_type  \
85540  262118ce178bb3e4590a3adcf6d62e6b                   1  credit_card

       payment_installments  payment_value
85540                     5         126.12

In [56]:
divergencias["diferenca"].describe()

count    300.000000
mean       9.570000
std       18.142737
min      -51.620000
25%        1.550000
50%        5.425000
75%       11.925000
max      182.810000
Name: diferenca, dtype: float64

In [57]:
divergencias["diferenca"].value_counts().head(20)

diferenca
 0.02     12
-0.02     10
-0.02      3
 0.02      3
-0.02      2
 0.02      2
 0.03      2
 5.17      2
 5.27      2
 6.89      2
-51.62     1
-21.80     1
-16.50     1
-14.99     1
-14.95     1
-13.76     1
-10.39     1
-10.00     1
-9.90      1
-8.99      1
Name: count, dtype: int64

In [58]:
comparacao_valores["diferenca_abs"] = (
    comparacao_valores["diferenca"].abs()
)

comparacao_valores["categoria_divergencia"] = np.select(
    [
        comparacao_valores["diferenca_abs"] <= 0.05,
        comparacao_valores["diferenca_abs"] <= 10,
        comparacao_valores["diferenca_abs"] <= 50,
        comparacao_valores["diferenca_abs"] > 50
    ],
    [
        "Até R$ 0,05",
        "R$ 0,06 a R$ 10",
        "R$ 10,01 a R$ 50",
        "Acima de R$ 50"
    ],
    default="Sem divergência"
)

comparacao_valores["categoria_divergencia"].value_counts()

categoria_divergencia
Até R$ 0,05         98405
R$ 0,06 a R$ 10       162
R$ 10,01 a R$ 50       90
Acima de R$ 50          8
Name: count, dtype: int64

In [59]:
divergencias_extremas = (
    comparacao_valores[
        comparacao_valores["diferenca_abs"] > 50
    ]
    .sort_values("diferenca", ascending=False)
)

divergencias_extremas[
    [
        "order_id",
        "valor_produtos",
        "valor_frete",
        "valor_itens_frete",
        "valor_pagamentos",
        "diferenca"
    ]
]

,order_id,valor_produtos,valor_frete,valor_itens_frete,valor_pagamentos,diferenca
79537,ce6d150fb29ada17d2082f4847107665,1299.00,104.66,1403.66,1586.47,182.81
42515,6e5fe7366a2e1bfbf3257dba0af1267f,179.19,108.72,287.91,406.92,119.01
43434,70b742795bc441e94a44a084b6d9ce7a,269.99,196.94,466.93,578.82,111.89
58752,996c7e73600ad3723e8627ab7bef81e4,559.90,28.00,587.90,664.43,76.53
43437,70b7e94ea46d3e8b5bc12a50186edaf0,167.88,45.27,213.15,274.84,61.69
72496,bc2c82b0ef78d2252b6176d1972db7c9,165.00,77.01,242.01,303.02,61.01
67466,af9ffff2ce6b3defd34fd4c78857a379,395.65,17.52,413.17,466.97,53.80
14628,262118ce178bb3e4590a3adcf6d62e6b,119.80,57.94,177.74,126.12,-51.62

In [60]:
pedidos_extremos = divergencias_extremas["order_id"].tolist()

df_payments[
    df_payments["order_id"].isin(pedidos_extremos)
].sort_values(
    ["order_id", "payment_sequential"]
)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
85540,262118ce178bb3e4590a3adcf6d62e6b,1,credit_card,5,126.12
38060,6e5fe7366a2e1bfbf3257dba0af1267f,1,credit_card,10,406.92
25761,70b742795bc441e94a44a084b6d9ce7a,1,credit_card,20,578.82
2970,70b7e94ea46d3e8b5bc12a50186edaf0,1,credit_card,24,274.84
61856,996c7e73600ad3723e8627ab7bef81e4,1,credit_card,10,664.43
4954,af9ffff2ce6b3defd34fd4c78857a379,1,credit_card,10,466.97
27307,bc2c82b0ef78d2252b6176d1972db7c9,1,credit_card,21,303.02
359,ce6d150fb29ada17d2082f4847107665,1,credit_card,10,1586.47

In [61]:
df_items[
    df_items["order_id"].isin(pedidos_extremos)
].sort_values(
    ["order_id", "order_item_id"]
)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
16662,262118ce178bb3e4590a3adcf6d62e6b,1,6aeed495dcb87dd06532f70dea6ebb5a,b56906f7fd1696e043f1bcce164c487b,2016-10-11 12:13:50,59.90,28.97
16663,262118ce178bb3e4590a3adcf6d62e6b,2,6aeed495dcb87dd06532f70dea6ebb5a,b56906f7fd1696e043f1bcce164c487b,2016-10-11 12:13:50,59.90,28.97
48566,6e5fe7366a2e1bfbf3257dba0af1267f,1,7721582bb750762d81850267d19881c1,0c8380b62e38e8a1e6adbeba7eb9688c,2016-10-14 12:02:21,19.83,17.00
48567,6e5fe7366a2e1bfbf3257dba0af1267f,2,65bb78cf0bbc3ca6406f30e6793736f9,391fc6631aebcf3004804e51b40bcf1e,2016-10-14 12:02:20,39.90,19.24
48568,6e5fe7366a2e1bfbf3257dba0af1267f,3,7721582bb750762d81850267d19881c1,0c8380b62e38e8a1e6adbeba7eb9688c,2016-10-14 12:02:21,19.83,17.00
48569,6e5fe7366a2e1bfbf3257dba0af1267f,4,65bb78cf0bbc3ca6406f30e6793736f9,391fc6631aebcf3004804e51b40bcf1e,2016-10-14 12:02:20,39.90,19.24
48570,6e5fe7366a2e1bfbf3257dba0af1267f,5,7721582bb750762d81850267d19881c1,0c8380b62e38e8a1e6adbeba7eb9688c,2016-10-14 12:02:21,19.83,17.00
48571,6e5fe7366a2e1bfbf3257dba0af1267f,6,65bb78cf0bbc3ca6406f30e6793736f9,391fc6631aebcf3004804e51b40bcf1e,2016-10-14 12:02:20,39.90,19.24
49611,70b742795bc441e94a44a084b6d9ce7a,1,1dd284c37ca97cbb86c029c65fb9a494,070d165398b553f3b4b851c216b8a358,2017-08-30 10:35:22,269.99,196.94
49614,70b7e94ea46d3e8b5bc12a50186edaf0,1,59ebd2c07d59483d0855b5b3d5e18728,ea8482cd71df3c1969d7b9473ff13abc,2018-01-05 13:17:25,27.99,21.06
49615,70b7e94ea46d3e8b5bc12a50186edaf0,2,7ea0b63dc9b8264702f2d2c1533fb4ae,634964b17796e64304cadf1ad3050fb7,2018-01-05 13:17:25,69.90,21.06
49616,70b7e94ea46d3e8b5bc12a50186edaf0,3,c1eee16d856657ad280936810ef3d080,014d9a685fd57276679edd00e07089e5,2018-01-05 13:17:25,69.99,3.15
67125,996c7e73600ad3723e8627ab7bef81e4,1,1f2b3e5d739add9d4596ba6de24204d4,269cff2d3c8d205c11f37a52402ea93b,2018-07-20 10:10:18,559.90,28.00
77132,af9ffff2ce6b3defd34fd4c78857a379,1,e3dd336775af78a83fc27ed85f0f15da,edb1ef5e36e0c8cd84eb3c9b003e486d,2018-02-21 10:30:38,395.65,17.52
82859,bc2c82b0ef78d2252b6176d1972db7c9,1,423b46d7ff817b1cd19ab195c7b76546,6560211a19b47992c3666cc44a7e94c0,2017-11-22 12:56:23,55.00,25.67
82860,bc2c82b0ef78d2252b6176d1972db7c9,2,423b46d7ff817b1cd19ab195c7b76546,6560211a19b47992c3666cc44a7e94c0,2017-11-22 12:56:23,55.00,25.67
82861,bc2c82b0ef78d2252b6176d1972db7c9,3,423b46d7ff817b1cd19ab195c7b76546,6560211a19b47992c3666cc44a7e94c0,2017-11-22 12:56:23,55.00,25.67
90875,ce6d150fb29ada17d2082f4847107665,1,638bbb2a5e4f360b71f332ddfebfd672,c4af86330efa7a2620772227d2d670c9,2018-02-07 12:31:37,1299.00,104.66

In [62]:
divergencias_com_data = divergencias.merge(
    df_orders[
        [
            "order_id",
            "order_purchase_timestamp",
            "order_status"
        ]
    ],
    on="order_id",
    how="left"
)

divergencias_com_data[
    [
        "order_id",
        "order_purchase_timestamp",
        "order_status",
        "diferenca"
    ]
].sort_values("order_purchase_timestamp").head(20)

,order_id,order_purchase_timestamp,order_status,diferenca
0,262118ce178bb3e4590a3adcf6d62e6b,2016-10-06 14:59:56,delivered,-51.62
5,0e556f5eafbf3eb399290101b183b10e,2016-10-06 18:50:25,delivered,-13.76
189,06d7e8a85f5cfef576c5303ed7d7f2e5,2016-10-07 12:06:30,delivered,8.30
298,6e5fe7366a2e1bfbf3257dba0af1267f,2016-10-09 22:36:25,delivered,119.01
237,2f9d4ee8ca77fe0951ebfe9064cad953,2016-10-09 23:38:19,delivered,14.12
185,03b218d39c422c250f389120c531b61f,2017-01-14 14:20:01,delivered,7.79
123,d2e9aead95751dd6bd0ce80e7d506c53,2017-01-16 23:25:16,delivered,3.84
28,e09dd765041e9934d762d51ccb26adee,2017-01-21 06:58:31,delivered,-0.02
218,469f0b908881368c45917f1bed8240ce,2017-01-24 21:35:25,delivered,10.97
36,8adafb3466daa5395694d3a906ff9d40,2017-01-25 15:47:27,delivered,-0.02
274,a52e6fa2d7c6ecaf73ff5f7f10438339,2017-01-28 20:09:18,delivered,26.97
235,9224db86cedf958891e1b1afb4ad570c,2017-01-30 10:12:59,delivered,13.78
190,b05922c45fc699ae9049a2c5add3e02a,2017-02-02 07:05:42,delivered,8.47
70,c253cb678b5c3b8e8c9a13fc97d8e7f5,2017-02-06 14:31:27,delivered,1.24
244,971d58b94f7bda9a79f4847e1509a433,2017-02-07 23:16:34,delivered,16.22
78,6aaedd714ad6929fc4df8d51bd4cfe9a,2017-02-08 22:58:15,delivered,1.67
164,b495ec18170fb28a3610c8d3ab464442,2017-02-10 11:11:16,delivered,6.09
156,4d4aac37e91472a2cbb36ee91d35866f,2017-02-14 23:19:29,delivered,5.69
151,74016effecaa79d592487f6a4ee47d4b,2017-02-18 10:39:14,delivered,5.45
66,f090de1b2ed9f4e251662cb31e3c7127,2017-02-22 10:10:52,shipped,0.92

In [63]:
divergencias_com_pagamento = divergencias.merge(
    df_payments[
        [
            "order_id",
            "payment_type",
            "payment_installments",
            "payment_sequential",
            "payment_value"
        ]
    ],
    on="order_id",
    how="left"
)

divergencias_com_pagamento[
    "payment_type"
].value_counts(dropna=False)

payment_type
credit_card    290
boleto          13
debit_card       7
voucher          7
Name: count, dtype: int64

In [64]:
analise_pagamento = (
    comparacao_valores
    .merge(
        df_payments[
            ["order_id", "payment_type"]
        ].drop_duplicates("order_id"),
        on="order_id",
        how="left"
    )
    .groupby("payment_type")
    .agg(
        total_pedidos=("order_id", "count"),
        pedidos_com_divergencia=("corresponde", lambda x: (~x).sum())
    )
    .reset_index()
)

analise_pagamento["taxa_divergencia"] = (
    analise_pagamento["pedidos_com_divergencia"]
    / analise_pagamento["total_pedidos"]
    * 100
)

analise_pagamento.sort_values(
    "taxa_divergencia",
    ascending=False
)

  payment_type  total_pedidos  pedidos_com_divergencia  taxa_divergencia
2   debit_card           1520                        7          0.460526
1  credit_card          74883                      278          0.371246
3      voucher           2648                        2          0.075529
0       boleto          19614                       13          0.066279

A tabela order_payments possui granularidade de registro de pagamento, permitindo múltiplos registros por pedido. Embora a maior parte dos pedidos apresente compatibilidade entre o valor registrado nos pagamentos e a soma de produtos e frete, foram identificadas 300 divergências entre 98.665 pedidos comparáveis. As divergências estão distribuídas ao longo do período analisado e apresentam baixa frequência relativa entre os diferentes tipos de pagamento. Dessa forma, payment_value não será utilizado como fonte primária para o cálculo da receita de produtos no CASE 01. A receita de produtos será calculada a partir de order_items.price, enquanto payment_value será tratado como uma variável relacionada ao comportamento de pagamento.

In [65]:
df_products = tabelas["olist_products_dataset"]

print("Dimensões:", df_products.shape)
print("\nColunas:")
print(df_products.columns.tolist())

print("\nTipos:")
print(df_products.dtypes)

print("\nValores nulos:")
print(df_products.isna().sum())

print("\nProdutos únicos:")
print(df_products["product_id"].nunique())

print("\nLinhas duplicadas:")
print(df_products.duplicated().sum())

Dimensões: (32951, 9)

Colunas:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Tipos:
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

Valores nulos:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Produtos únicos:
32951

Linhas duplicadas:
0

In [66]:
produtos_nos_itens = set(df_items["product_id"].unique())
produtos_na_tabela = set(df_products["product_id"].unique())

itens_sem_produto = produtos_nos_itens - produtos_na_tabela
produtos_sem_vendas = produtos_na_tabela - produtos_nos_itens

print("Produtos presentes em order_items:", len(produtos_nos_itens))
print("Produtos presentes em products:", len(produtos_na_tabela))

print("\nProdutos vendidos que NÃO existem em products:",
      len(itens_sem_produto))

print("Produtos em products que NÃO aparecem em order_items:",
      len(produtos_sem_vendas))

Produtos presentes em order_items: 32951
Produtos presentes em products: 32951

Produtos vendidos que NÃO existem em products: 0
Produtos em products que NÃO aparecem em order_items: 0

In [67]:
print("Categorias únicas:", df_products["product_category_name"].nunique())

print("\nProdutos sem categoria:",
      df_products["product_category_name"].isna().sum())

print("\nCategorias com maior quantidade de produtos:")
print(
    df_products["product_category_name"]
    .value_counts(dropna=False)
    .head(20)
)

Categorias únicas: 73

Produtos sem categoria: 610

Categorias com maior quantidade de produtos:
product_category_name
cama_mesa_banho                      3029
esporte_lazer                        2867
moveis_decoracao                     2657
beleza_saude                         2444
utilidades_domesticas                2335
automotivo                           1900
informatica_acessorios               1639
brinquedos                           1411
relogios_presentes                   1329
telefonia                            1134
bebes                                 919
perfumaria                            868
papelaria                             849
fashion_bolsas_e_acessorios           849
cool_stuff                            789
ferramentas_jardim                    753
pet_shop                              719
NaN                                   610
eletronicos                           517
construcao_ferramentas_construcao     400
Name: count, dtype: int64

In [68]:
produtos_sem_categoria = df_products.loc[
    df_products["product_category_name"].isna(),
    "product_id"
]

itens_sem_categoria = df_items[
    df_items["product_id"].isin(produtos_sem_categoria)
]

print("Produtos sem categoria:", len(produtos_sem_categoria))

print(
    "Produtos sem categoria que aparecem em order_items:",
    itens_sem_categoria["product_id"].nunique()
)

print(
    "Linhas de venda relacionadas a produtos sem categoria:",
    len(itens_sem_categoria)
)

print(
    "Percentual das linhas de venda relacionadas a produtos sem categoria:",
    round(
        len(itens_sem_categoria) / len(df_items) * 100,
        2
    ),
    "%"
)

Produtos sem categoria: 610
Produtos sem categoria que aparecem em order_items: 610
Linhas de venda relacionadas a produtos sem categoria: 1603
Percentual das linhas de venda relacionadas a produtos sem categoria: 1.42 %

In [69]:
colunas_fisicas = [
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

print("Valores nulos:")
print(df_products[colunas_fisicas].isna().sum())

print("\nValores iguais a zero:")
print((df_products[colunas_fisicas] == 0).sum())

print("\nValores negativos:")
print((df_products[colunas_fisicas] < 0).sum())

Valores nulos:
product_weight_g     2
product_length_cm    2
product_height_cm    2
product_width_cm     2
dtype: int64

Valores iguais a zero:
product_weight_g     4
product_length_cm    0
product_height_cm    0
product_width_cm     0
dtype: int64

Valores negativos:
product_weight_g     0
product_length_cm    0
product_height_cm    0
product_width_cm     0
dtype: int64

In [70]:
produtos_com_problemas_fisicos = df_products[
    df_products[
        [
            "product_weight_g",
            "product_length_cm",
            "product_height_cm",
            "product_width_cm"
        ]
    ].isna().any(axis=1)
    |
    (df_products["product_weight_g"] == 0)
]

print(
    produtos_com_problemas_fisicos[
        [
            "product_id",
            "product_category_name",
            "product_weight_g",
            "product_length_cm",
            "product_height_cm",
            "product_width_cm"
        ]
    ]
)

                             product_id product_category_name  \
8578   09ff539a621711667c43eba6a3bd8466                 bebes
9769   81781c0fed9fe1ad6e8c81fca1e1cb08       cama_mesa_banho
13683  8038040ee2a71048d4bdbbdc985b69ab       cama_mesa_banho
14997  36ba42dd187055e1fbe943b2d11430ca       cama_mesa_banho
18851  5eb564652db742ff8f28759cd8d2652a                   NaN
32079  e673e90efa65a5409ff4196c038bb5af       cama_mesa_banho

       product_weight_g  product_length_cm  product_height_cm  \
8578                NaN                NaN                NaN
9769                0.0               30.0               25.0
13683               0.0               30.0               25.0
14997               0.0               30.0               25.0
18851               NaN                NaN                NaN
32079               0.0               30.0               25.0

       product_width_cm
8578                NaN
9769               30.0
13683              30.0
14997              30.0
18851               NaN
32079              30.0

In [71]:
ids_produtos_problema = produtos_com_problemas_fisicos["product_id"]

vendas_produtos_problema = df_items[
    df_items["product_id"].isin(ids_produtos_problema)
]

print(
    "Produtos com inconsistência física que possuem vendas:",
    vendas_produtos_problema["product_id"].nunique()
)

print(
    "Linhas de venda desses produtos:",
    len(vendas_produtos_problema)
)

print("\nVendas por produto:")
print(
    vendas_produtos_problema
    .groupby("product_id")
    .agg(
        linhas_venda=("product_id", "size"),
        quantidade_unidades=("order_item_id", "count"),
        receita_produtos=("price", "sum")
    )
    .sort_values("receita_produtos", ascending=False)
)

Produtos com inconsistência física que possuem vendas: 6
Linhas de venda desses produtos: 26

Vendas por produto:
                                  linhas_venda  quantidade_unidades  \
product_id
09ff539a621711667c43eba6a3bd8466             1                    1
5eb564652db742ff8f28759cd8d2652a            17                   17
e673e90efa65a5409ff4196c038bb5af             4                    4
36ba42dd187055e1fbe943b2d11430ca             2                    2
8038040ee2a71048d4bdbbdc985b69ab             1                    1
81781c0fed9fe1ad6e8c81fca1e1cb08             1                    1

                                  receita_produtos
product_id
09ff539a621711667c43eba6a3bd8466            1934.0
5eb564652db742ff8f28759cd8d2652a             563.0
e673e90efa65a5409ff4196c038bb5af             519.6
36ba42dd187055e1fbe943b2d11430ca             200.0
8038040ee2a71048d4bdbbdc985b69ab             129.9
81781c0fed9fe1ad6e8c81fca1e1cb08             100.0

In [72]:
df_translation = tabelas["product_category_name_translation"]

print("Dimensões:", df_translation.shape)

print("\nColunas:")
print(df_translation.columns.tolist())

print("\nCategorias únicas:")
print(df_translation["product_category_name"].nunique())

print("\nCategorias em inglês únicas:")
print(df_translation["product_category_name_english"].nunique())

print("\nValores nulos:")
print(df_translation.isna().sum())

print("\nDuplicatas:")
print(df_translation.duplicated().sum())

Dimensões: (71, 2)

Colunas:
['product_category_name', 'product_category_name_english']

Categorias únicas:
71

Categorias em inglês únicas:
71

Valores nulos:
product_category_name            0
product_category_name_english    0
dtype: int64

Duplicatas:
0

In [73]:
categorias_products = set(
    df_products["product_category_name"].dropna().unique()
)

categorias_translation = set(
    df_translation["product_category_name"].unique()
)

categorias_sem_traducao = categorias_products - categorias_translation
categorias_sem_produtos = categorias_translation - categorias_products

print("Categorias não nulas em products:",
      len(categorias_products))

print("Categorias na tabela de tradução:",
      len(categorias_translation))

print("\nCategorias de products sem tradução:",
      len(categorias_sem_traducao))

print(categorias_sem_traducao)

print("\nCategorias traduzidas sem produtos:",
      len(categorias_sem_produtos))

print(categorias_sem_produtos)

Categorias não nulas em products: 73
Categorias na tabela de tradução: 71

Categorias de products sem tradução: 2
{'pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos'}

Categorias traduzidas sem produtos: 0
set()

In [74]:
categorias_sem_traducao = [
    "pc_gamer",
    "portateis_cozinha_e_preparadores_de_alimentos"
]

produtos_sem_traducao = df_products[
    df_products["product_category_name"].isin(categorias_sem_traducao)
][
    ["product_id", "product_category_name"]
]

vendas_sem_traducao = df_items.merge(
    produtos_sem_traducao,
    on="product_id",
    how="inner"
)

print("Produtos nas categorias sem tradução:",
      produtos_sem_traducao["product_id"].nunique())

print("Linhas de venda:",
      len(vendas_sem_traducao))

print("\nResumo por categoria:")
print(
    vendas_sem_traducao
    .groupby("product_category_name")
    .agg(
        produtos=("product_id", "nunique"),
        linhas_venda=("product_id", "size"),
        receita_produtos=("price", "sum")
    )
    .sort_values("receita_produtos", ascending=False)
)

Produtos nas categorias sem tradução: 13
Linhas de venda: 24

Resumo por categoria:
                                               produtos  linhas_venda  \
product_category_name
portateis_cozinha_e_preparadores_de_alimentos        10            15
pc_gamer                                              3             9

                                               receita_produtos
product_category_name
portateis_cozinha_e_preparadores_de_alimentos           3968.53
pc_gamer                                                1545.95

In [75]:
df_sellers = tabelas["olist_sellers_dataset"]

print("Dimensões:", df_sellers.shape)

print("\nColunas:")
print(df_sellers.columns.tolist())

print("\nTipos:")
print(df_sellers.dtypes)

print("\nValores nulos:")
print(df_sellers.isna().sum())

print("\nSellers únicos:")
print(df_sellers["seller_id"].nunique())

print("\nDuplicatas completas:")
print(df_sellers.duplicated().sum())

Dimensões: (3095, 4)

Colunas:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

Tipos:
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

Valores nulos:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Sellers únicos:
3095

Duplicatas completas:
0

In [76]:
sellers_nos_itens = set(df_items["seller_id"].unique())
sellers_na_tabela = set(df_sellers["seller_id"].unique())

sellers_sem_cadastro = sellers_nos_itens - sellers_na_tabela
sellers_sem_vendas = sellers_na_tabela - sellers_nos_itens

print("Sellers presentes em order_items:",
      len(sellers_nos_itens))

print("Sellers presentes em sellers:",
      len(sellers_na_tabela))

print("\nSellers em order_items sem cadastro em sellers:",
      len(sellers_sem_cadastro))

print("Sellers cadastrados sem vendas em order_items:",
      len(sellers_sem_vendas))

Sellers presentes em order_items: 3095
Sellers presentes em sellers: 3095

Sellers em order_items sem cadastro em sellers: 0
Sellers cadastrados sem vendas em order_items: 0

In [77]:
print("Estados dos sellers:")
print(df_sellers["seller_state"].value_counts())

print("\nQuantidade de cidades:")
print(df_sellers["seller_city"].nunique())

print("\nQuantidade de CEPs:")
print(df_sellers["seller_zip_code_prefix"].nunique())

Estados dos sellers:
seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
AC       1
PI       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

Quantidade de cidades:
611

Quantidade de CEPs:
2246

In [78]:
vendas_por_seller = (
    df_items
    .groupby("seller_id")
    .agg(
        linhas_venda=("seller_id", "size"),
        receita_produtos=("price", "sum")
    )
    .reset_index()
)

print("Sellers analisados:", vendas_por_seller["seller_id"].nunique())

print("\nEstatísticas das linhas de venda por seller:")
print(vendas_por_seller["linhas_venda"].describe())

print("\nEstatísticas da receita por seller:")
print(vendas_por_seller["receita_produtos"].describe())

Sellers analisados: 3095

Estatísticas das linhas de venda por seller:

count    3095.000000
mean       36.397415
std       119.193461
min         1.000000
25%         2.000000
50%         8.000000
75%        24.000000
max      2033.000000
Name: linhas_venda, dtype: float64

Estatísticas da receita por seller:
count      3095.000000
mean       4391.484233
std       13921.997192
min           3.500000
25%         208.850000
50%         821.480000
75%        3280.830000
max      229472.630000
Name: receita_produtos, dtype: float64

In [79]:
estrutura_seller_estado = (
    df_sellers
    .merge(
        vendas_por_seller,
        on="seller_id",
        how="left"
    )
    .groupby("seller_state")
    .agg(
        sellers=("seller_id", "nunique"),
        linhas_venda=("linhas_venda", "sum"),
        receita_produtos=("receita_produtos", "sum")
    )
    .sort_values("receita_produtos", ascending=False)
)

print(estrutura_seller_estado)

              sellers  linhas_venda  receita_produtos
seller_state
SP               1849         80342        8753396.21
PR                349          8671        1261887.21
MG                244          8827        1011564.74
RJ                171          4818         843984.22
SC                190          4075         632426.07
RS                129          2199         378559.54
BA                 19           643         285561.56
DF                 30           899          97749.48
PE                  9           448          91493.85
GO                 40           520          66399.21
ES                 23           372          47689.61
MA                  1           405          36408.95
CE                 13            94          20240.64
PB                  6            38          17095.00
MT                  4           145          17070.72
RN                  5            56           9992.60
MS                  5            50           8551.69
RO                  2            14           4762.20
PI                  1            12           2522.00
SE                  2            10           1606.20
PA                  1             8           1238.00
AM                  1             3           1177.00
AC                  1             1            267.00

In [80]:
df_reviews = tabelas["olist_order_reviews_dataset"]

print("Dimensões:", df_reviews.shape)

print("\nColunas:")
print(df_reviews.columns.tolist())

print("\nTipos:")
print(df_reviews.dtypes)

print("\nValores nulos:")
print(df_reviews.isna().sum())

print("\nIDs de pedido únicos:")
print(df_reviews["order_id"].nunique())

print("\nDuplicatas completas:")
print(df_reviews.duplicated().sum())

Dimensões: (99224, 7)

Colunas:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

Tipos:
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

Valores nulos:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

IDs de pedido únicos:
98673

Duplicatas completas:
0

In [81]:
reviews_por_pedido = (
    df_reviews
    .groupby("order_id")
    .size()
)

print("Pedidos com review:", reviews_por_pedido.size)

print("\nDistribuição de reviews por pedido:")
print(reviews_por_pedido.value_counts().sort_index())

print("\nMáximo de reviews para um pedido:",
      reviews_por_pedido.max())

Pedidos com review: 98673

Distribuição de reviews por pedido:
1    98126
2      543
3        4
Name: count, dtype: int64

Máximo de reviews para um pedido: 3

In [82]:
orders_com_review = set(df_reviews["order_id"].unique())
orders_na_tabela = set(df_orders["order_id"].unique())

reviews_sem_pedido = orders_com_review - orders_na_tabela
pedidos_sem_review = orders_na_tabela - orders_com_review

print("Pedidos em reviews:", len(orders_com_review))
print("Pedidos em orders:", len(orders_na_tabela))

print("\nReviews cujo order_id NÃO existe em orders:",
      len(reviews_sem_pedido))

print("Pedidos sem review:",
      len(pedidos_sem_review))

Pedidos em reviews: 98673
Pedidos em orders: 99441

Reviews cujo order_id NÃO existe em orders: 0
Pedidos sem review: 768

In [83]:
print("Distribuição das notas:")
print(df_reviews["review_score"].value_counts().sort_index())

print("\nPercentual das notas:")
print(
    df_reviews["review_score"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

Distribuição das notas:
review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

Percentual das notas:
review_score
1    11.51
2     3.18
3     8.24
4    19.29
5    57.78
Name: proportion, dtype: float64

In [84]:
print("Reviews com título:")
print(df_reviews["review_comment_title"].notna().sum())

print("\nReviews com mensagem:")
print(df_reviews["review_comment_message"].notna().sum())

print("\nReviews sem título E sem mensagem:")
print(
    (
        df_reviews["review_comment_title"].isna()
        & df_reviews["review_comment_message"].isna()
    ).sum()
)

Reviews com título:
11568

Reviews com mensagem:
40977

Reviews sem título E sem mensagem:
56518

In [85]:
print("Reviews totais:", len(df_reviews))

print("review_id únicos:",
      df_reviews["review_id"].nunique())

print("\nDuplicatas de review_id:",
      df_reviews["review_id"].duplicated().sum())

print("\nDuplicatas de (order_id, review_id):",
      df_reviews.duplicated(
          subset=["order_id", "review_id"]
      ).sum())

Reviews totais: 99224
review_id únicos: 98410

Duplicatas de review_id: 814

Duplicatas de (order_id, review_id): 0

In [86]:
reviews_id_repetidos = (
    df_reviews["review_id"]
    .value_counts()
    .loc[lambda x: x > 1]
)

print("Quantidade de review_id repetidos:",
      len(reviews_id_repetidos))

print("\nDistribuição da quantidade de ocorrências:")
print(reviews_id_repetidos.value_counts().sort_index())

print("\nMaior número de ocorrências de um mesmo review_id:",
      reviews_id_repetidos.max())

Quantidade de review_id repetidos: 789

Distribuição da quantidade de ocorrências:
count
2    764
3     25
Name: count, dtype: int64

Maior número de ocorrências de um mesmo review_id: 3

In [87]:
exemplos_review_repetido = (
    df_reviews[
        df_reviews["review_id"].isin(reviews_id_repetidos.index)
    ]
    .sort_values("review_id")
)

print(
    exemplos_review_repetido[
        [
            "review_id",
            "order_id",
            "review_score",
            "review_creation_date"
        ]
    ].head(20).to_string(index=False)
)

                       review_id                         order_id  review_score review_creation_date
00130cbe1f9d422698c812ed8ded1919 dfcdfc43867d1c1381bfaf62d6b9c195             1  2018-03-07 00:00:00
00130cbe1f9d422698c812ed8ded1919 04a28263e085d399c97ae49e0b477efa             1  2018-03-07 00:00:00
0115633a9c298b6a98bcbe4eee75345f 78a4201f58af3463bdab842eea4bc801             5  2017-09-21 00:00:00
0115633a9c298b6a98bcbe4eee75345f 0c9850b2c179c1ef60d2855e2751d1fa             5  2017-09-21 00:00:00
0174caf0ee5964646040cd94e15ac95e f93a732712407c02dce5dd5088d0f47b             1  2018-03-07 00:00:00
0174caf0ee5964646040cd94e15ac95e 74db91e33b4e1fd865356c89a61abf1f             1  2018-03-07 00:00:00
017808d29fd1f942d97e50184dfb4c13 8daaa9e99d60fbba579cc1c3e3bfae01             5  2018-03-02 00:00:00
017808d29fd1f942d97e50184dfb4c13 b1461c8882153b5fe68307c46a506e39             5  2018-03-02 00:00:00
0254bd905dc677a6078990aad3331a36 5bf226cf882c5bf4247f89a97c86f273             1  2017-09-09 00:00:00
0254bd905dc677a6078990aad3331a36 331b367bdd766f3d1cf518777317b5d9             1  2017-09-09 00:00:00
0288d42bef3dfe36930740c9588a570f 33d8795f04dd631f3480d7aaf90da3dc             3  2017-07-29 00:00:00
0288d42bef3dfe36930740c9588a570f f889a5a0b44adc29c5465b99395ac3c1             3  2017-07-29 00:00:00
02aa7f5f75e964e3c7efa59a1f515281 d8e17d5f7dacf0970d316e7c03e741e8             3  2017-07-27 00:00:00
02aa7f5f75e964e3c7efa59a1f515281 db92613c074f00e53066388d48ad7512             3  2017-07-27 00:00:00
034528cb00b6bc981847acafbdf2ae0b e1e8e3bca903de27e9a1c72b5a5795e0             1  2017-05-14 00:00:00
034528cb00b6bc981847acafbdf2ae0b 3d3742a96f24a8fe4e2e57628807e476             1  2017-05-14 00:00:00
03a6a25db577d0689440933055111897 2acfdc5131ff2cf4433e668454c9784c             5  2017-12-15 00:00:00
03a6a25db577d0689440933055111897 3fde8b7313af6b37b84b5c7594d7add0             5  2017-12-15 00:00:00
0467560f511c516ddaa54a60edb0c291 0c995611a99f81268d859184a416f1db             5  2017-02-09 00:00:00
0467560f511c516ddaa54a60edb0c291 55b2e390d5d80ada31ad1b795ebeb087             5  2017-02-09 00:00:00

In [88]:
notas_por_pedido = (
    df_reviews
    .groupby("order_id")["review_score"]
    .nunique()
)

print("Pedidos com mais de uma review:",
      (reviews_por_pedido > 1).sum())

print("\nPedidos com múltiplas reviews e notas diferentes:",
      ((reviews_por_pedido > 1) & (notas_por_pedido > 1)).sum())

print("\nDistribuição da quantidade de notas distintas:")
print(
    notas_por_pedido[reviews_por_pedido > 1]
    .value_counts()
    .sort_index()
)

Pedidos com mais de uma review: 547

Pedidos com múltiplas reviews e notas diferentes: 202

Distribuição da quantidade de notas distintas:
review_score
1    345
2    202
Name: count, dtype: int64

In [89]:
reviews_multiplas = df_reviews[
    df_reviews["order_id"].isin(
        reviews_por_pedido[reviews_por_pedido > 1].index
    )
].copy()

reviews_multiplas["review_creation_date"] = pd.to_datetime(
    reviews_multiplas["review_creation_date"]
)

datas_por_pedido = (
    reviews_multiplas
    .groupby("order_id")["review_creation_date"]
    .agg(
        quantidade_datas="nunique",
        primeira_data="min",
        ultima_data="max"
    )
)

print("Pedidos com múltiplas reviews:",
      len(datas_por_pedido))

print("\nDistribuição da quantidade de datas distintas:")
print(
    datas_por_pedido["quantidade_datas"]
    .value_counts()
    .sort_index()
)

print("\nPedidos com múltiplas reviews em datas diferentes:",
      (datas_por_pedido["quantidade_datas"] > 1).sum())

Pedidos com múltiplas reviews: 547

Distribuição da quantidade de datas distintas:
quantidade_datas
1    155
2    390
3      2
Name: count, dtype: int64

Pedidos com múltiplas reviews em datas diferentes: 392

In [90]:
estrutura_reviews = (
    reviews_multiplas
    .groupby("order_id")
    .agg(
        quantidade_reviews=("review_id", "size"),
        quantidade_notas=("review_score", "nunique"),
        quantidade_datas=("review_creation_date", "nunique")
    )
)

estrutura_reviews["notas_diferentes"] = (
    estrutura_reviews["quantidade_notas"] > 1
)

estrutura_reviews["datas_diferentes"] = (
    estrutura_reviews["quantidade_datas"] > 1
)

estrutura_reviews["estrutura"] = "mesma data + mesma nota"

estrutura_reviews.loc[
    (~estrutura_reviews["datas_diferentes"])
    & (estrutura_reviews["notas_diferentes"]),
    "estrutura"
] = "mesma data + notas diferentes"

estrutura_reviews.loc[
    (estrutura_reviews["datas_diferentes"])
    & (~estrutura_reviews["notas_diferentes"]),
    "estrutura"
] = "datas diferentes + mesma nota"

estrutura_reviews.loc[
    (estrutura_reviews["datas_diferentes"])
    & (estrutura_reviews["notas_diferentes"]),
    "estrutura"
] = "datas diferentes + notas diferentes"

print(
    estrutura_reviews["estrutura"]
    .value_counts()
)

estrutura
datas diferentes + mesma nota          220
datas diferentes + notas diferentes    172
mesma data + mesma nota                125
mesma data + notas diferentes           30
Name: count, dtype: int64

In [91]:
texto_por_pedido = (
    reviews_multiplas
    .assign(
        texto_completo=lambda x: (
            x["review_comment_title"].fillna("")
            + " | "
            + x["review_comment_message"].fillna("")
        ).str.strip()
    )
    .groupby("order_id")["texto_completo"]
    .nunique()
)

print("Pedidos com múltiplas reviews:",
      len(texto_por_pedido))

print("\nDistribuição da quantidade de textos distintos:")
print(
    texto_por_pedido
    .value_counts()
    .sort_index()
)

print("\nPedidos com textos diferentes entre as reviews:",
      (texto_por_pedido > 1).sum())

Pedidos com múltiplas reviews: 547

Distribuição da quantidade de textos distintos:
texto_completo
1    313
2    232
3      2
Name: count, dtype: int64

Pedidos com textos diferentes entre as reviews: 234

# Data Profiling

## Objetivo

Caracterizar o comportamento das vendas ao longo do período observado,
estabelecer uma linha de base do desempenho comercial e identificar
dimensões que apresentem sinais de deterioração.

Nesta etapa, o objetivo é descrever e caracterizar os dados.

As análises realizadas aqui não têm como finalidade estabelecer causalidade.
As hipóteses explicativas serão investigadas posteriormente nas etapas de
EDA e análise estatística.

In [92]:
import pandas as pd

In [93]:
orders_path = "../data/raw/olist_orders_dataset.csv"
order_items_path = "../data/raw/olist_order_items_dataset.csv"

In [94]:
orders = pd.read_csv(orders_path)

In [95]:
orders.shape

(99441, 8)

In [96]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [97]:
orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [98]:
orders["order_purchase_timestamp"].head()

0    2017-10-02 10:56:33
1    2018-07-24 20:41:37
2    2018-08-08 08:38:49
3    2017-11-18 19:28:06
4    2018-02-13 21:18:39
Name: order_purchase_timestamp, dtype: str

In [99]:
orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"]
)

In [100]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                           str
order_delivered_carrier_date                str
order_delivered_customer_date               str
order_estimated_delivery_date               str
dtype: object

In [101]:
orders["order_purchase_timestamp"].isna().sum()

np.int64(0)

In [102]:
order_items = pd.read_csv(order_items_path)

In [103]:
order_items.shape

(112650, 7)

In [104]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [105]:
order_items.dtypes

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

In [106]:
order_items.duplicated(
    subset=["order_id", "order_item_id"]
).sum()

np.int64(0)

In [107]:
order_items["order_id"].isin(orders["order_id"]).mean()

np.float64(1.0)

In [108]:
orders["order_id"].isin(order_items["order_id"]).value_counts()

order_id
True     98666
False      775
Name: count, dtype: int64

In [109]:
orders.loc[
    ~orders["order_id"].isin(order_items["order_id"]),
    "order_status"
].value_counts()

order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [110]:
sales_base = order_items.merge(
    orders[
        [
            "order_id",
            "order_purchase_timestamp",
            "order_status"
        ]
    ],
    on="order_id",
    how="left"
)

In [111]:
sales_base.shape

(112650, 9)

In [112]:
sales_base.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value',
       'order_purchase_timestamp', 'order_status'],
      dtype='str')

In [113]:
sales_base[
    [
        "order_purchase_timestamp",
        "order_status"
    ]
].isna().sum()

order_purchase_timestamp    0
order_status                0
dtype: int64

In [114]:
sales_base["order_purchase_timestamp"].agg(["min", "max"])

min   2016-09-04 21:15:19
max   2018-09-03 09:06:57
Name: order_purchase_timestamp, dtype: datetime64[us]

In [115]:
sales_base["purchase_month"] = sales_base["order_purchase_timestamp"].dt.to_period("M")

In [116]:
sales_base["purchase_month"].head()

0    2017-09
1    2017-04
2    2018-01
3    2018-08
4    2017-02
Name: purchase_month, dtype: period[M]

In [117]:
sales_base["purchase_month"].value_counts().sort_index()

purchase_month
2016-09       6
2016-10     363
2016-12       1
2017-01     955
2017-02    1951
2017-03    3000
2017-04    2684
2017-05    4136
2017-06    3583
2017-07    4519
2017-08    4910
2017-09    4831
2017-10    5322
2017-11    8665
2017-12    6308
2018-01    8208
2018-02    7672
2018-03    8217
2018-04    7975
2018-05    7925
2018-06    7078
2018-07    7092
2018-08    7248
2018-09       1
Freq: M, Name: count, dtype: int64

In [118]:
monthly_revenue = (
    sales_base
    .groupby("purchase_month")["price"]
    .sum()
)

In [119]:
monthly_revenue

purchase_month
2016-09        267.36
2016-10      49507.66
2016-12         10.90
2017-01     120312.87
2017-02     247303.02
2017-03     374344.30
2017-04     359927.23
2017-05     506071.14
2017-06     433038.60
2017-07     498031.48
2017-08     573971.68
2017-09     624401.69
2017-10     664219.43
2017-11    1010271.37
2017-12     743914.17
2018-01     950030.36
2018-02     844178.71
2018-03     983213.44
2018-04     996647.75
2018-05     996517.68
2018-06     865124.31
2018-07     895507.22
2018-08     854686.33
2018-09        145.00
Freq: M, Name: price, dtype: float64

In [120]:
monthly_orders = (
    sales_base
    .groupby("purchase_month")["order_id"]
    .nunique()
)

In [121]:
monthly_orders

purchase_month
2016-09       3
2016-10     308
2016-12       1
2017-01     789
2017-02    1733
2017-03    2641
2017-04    2391
2017-05    3660
2017-06    3217
2017-07    3969
2017-08    4293
2017-09    4243
2017-10    4568
2017-11    7451
2017-12    5624
2018-01    7220
2018-02    6694
2018-03    7188
2018-04    6934
2018-05    6853
2018-06    6160
2018-07    6273
2018-08    6452
2018-09       1
Freq: M, Name: order_id, dtype: int64

In [122]:
monthly_items = (
    sales_base
    .groupby("purchase_month")["order_item_id"]
    .count()
)

In [123]:
monthly_items

purchase_month
2016-09       6
2016-10     363
2016-12       1
2017-01     955
2017-02    1951
2017-03    3000
2017-04    2684
2017-05    4136
2017-06    3583
2017-07    4519
2017-08    4910
2017-09    4831
2017-10    5322
2017-11    8665
2017-12    6308
2018-01    8208
2018-02    7672
2018-03    8217
2018-04    7975
2018-05    7925
2018-06    7078
2018-07    7092
2018-08    7248
2018-09       1
Freq: M, Name: order_item_id, dtype: int64

In [124]:
monthly_ticket = monthly_revenue / monthly_orders

In [125]:
monthly_ticket

purchase_month
2016-09     89.120000
2016-10    160.739156
2016-12     10.900000
2017-01    152.487795
2017-02    142.702262
2017-03    141.743393
2017-04    150.534182
2017-05    138.270803
2017-06    134.609450
2017-07    125.480343
2017-08    133.699436
2017-09    147.160427
2017-10    145.407056
2017-11    135.588695
2017-12    132.274924
2018-01    131.583152
2018-02    126.109756
2018-03    136.785398
2018-04    143.733451
2018-05    145.413349
2018-06    140.442258
2018-07    142.755814
2018-08    132.468433
2018-09    145.000000
Freq: M, dtype: float64

In [126]:
monthly_profile = pd.DataFrame({
    "revenue": monthly_revenue,
    "orders": monthly_orders,
    "items": monthly_items,
    "ticket": monthly_ticket
})

In [127]:
monthly_profile

                   revenue  orders  items      ticket
purchase_month
2016-09             267.36       3      6   89.120000
2016-10           49507.66     308    363  160.739156
2016-12              10.90       1      1   10.900000
2017-01          120312.87     789    955  152.487795
2017-02          247303.02    1733   1951  142.702262
2017-03          374344.30    2641   3000  141.743393
2017-04          359927.23    2391   2684  150.534182
2017-05          506071.14    3660   4136  138.270803
2017-06          433038.60    3217   3583  134.609450
2017-07          498031.48    3969   4519  125.480343
2017-08          573971.68    4293   4910  133.699436
2017-09          624401.69    4243   4831  147.160427
2017-10          664219.43    4568   5322  145.407056
2017-11         1010271.37    7451   8665  135.588695
2017-12          743914.17    5624   6308  132.274924
2018-01          950030.36    7220   8208  131.583152
2018-02          844178.71    6694   7672  126.109756
2018-03          983213.44    7188   8217  136.785398
2018-04          996647.75    6934   7975  143.733451
2018-05          996517.68    6853   7925  145.413349
2018-06          865124.31    6160   7078  140.442258
2018-07          895507.22    6273   7092  142.755814
2018-08          854686.33    6452   7248  132.468433
2018-09             145.00       1      1  145.000000

In [128]:
sales_base["purchase_date"] = sales_base["order_purchase_timestamp"].dt.date

In [129]:
monthly_days = (
    sales_base
    .groupby("purchase_month")["purchase_date"]
    .nunique()
)

In [130]:
monthly_days

purchase_month
2016-09     3
2016-10     9
2016-12     1
2017-01    27
2017-02    28
2017-03    31
2017-04    30
2017-05    31
2017-06    30
2017-07    31
2017-08    31
2017-09    30
2017-10    31
2017-11    30
2017-12    31
2018-01    31
2018-02    28
2018-03    31
2018-04    30
2018-05    31
2018-06    30
2018-07    31
2018-08    29
2018-09     1
Freq: M, Name: purchase_date, dtype: int64

In [131]:
expected_days = monthly_profile.index.days_in_month

monthly_profile["days_observed"] = monthly_days
monthly_profile["days_expected"] = expected_days

In [132]:
monthly_profile

,revenue,orders,items,ticket,days_observed,days_expected
purchase_month,,,,,,
2016-09,267.36,3,6,89.120000,3,30
2016-10,49507.66,308,363,160.739156,9,31
2016-12,10.90,1,1,10.900000,1,31
2017-01,120312.87,789,955,152.487795,27,31
2017-02,247303.02,1733,1951,142.702262,28,28
2017-03,374344.30,2641,3000,141.743393,31,31
2017-04,359927.23,2391,2684,150.534182,30,30
2017-05,506071.14,3660,4136,138.270803,31,31
2017-06,433038.60,3217,3583,134.609450,30,30
2017-07,498031.48,3969,4519,125.480343,31,31
2017-08,573971.68,4293,4910,133.699436,31,31
2017-09,624401.69,4243,4831,147.160427,30,30
2017-10,664219.43,4568,5322,145.407056,31,31
2017-11,1010271.37,7451,8665,135.588695,30,30
2017-12,743914.17,5624,6308,132.274924,31,31
2018-01,950030.36,7220,8208,131.583152,31,31
2018-02,844178.71,6694,7672,126.109756,28,28
2018-03,983213.44,7188,8217,136.785398,31,31
2018-04,996647.75,6934,7975,143.733451,30,30
2018-05,996517.68,6853,7925,145.413349,31,31
2018-06,865124.31,6160,7078,140.442258,30,30
2018-07,895507.22,6273,7092,142.755814,31,31
2018-08,854686.33,6452,7248,132.468433,29,31
2018-09,145.00,1,1,145.000000,1,30

In [133]:
monthly_profile["coverage"] = (
    monthly_profile["days_observed"]
    == monthly_profile["days_expected"]
)

In [134]:
monthly_profile["coverage"].value_counts()

coverage
True     18
False     6
Name: count, dtype: int64

In [135]:
complete_monthly_profile = monthly_profile[
    monthly_profile["coverage"]
].copy()

In [136]:
complete_monthly_profile

,revenue,orders,items,ticket,days_observed,days_expected,coverage
purchase_month,,,,,,,
2017-02,247303.02,1733,1951,142.702262,28,28,True
2017-03,374344.30,2641,3000,141.743393,31,31,True
2017-04,359927.23,2391,2684,150.534182,30,30,True
2017-05,506071.14,3660,4136,138.270803,31,31,True
2017-06,433038.60,3217,3583,134.609450,30,30,True
2017-07,498031.48,3969,4519,125.480343,31,31,True
2017-08,573971.68,4293,4910,133.699436,31,31,True
2017-09,624401.69,4243,4831,147.160427,30,30,True
2017-10,664219.43,4568,5322,145.407056,31,31,True
2017-11,1010271.37,7451,8665,135.588695,30,30,True
2017-12,743914.17,5624,6308,132.274924,31,31,True
2018-01,950030.36,7220,8208,131.583152,31,31,True
2018-02,844178.71,6694,7672,126.109756,28,28,True
2018-03,983213.44,7188,8217,136.785398,31,31,True
2018-04,996647.75,6934,7975,143.733451,30,30,True
2018-05,996517.68,6853,7925,145.413349,31,31,True
2018-06,865124.31,6160,7078,140.442258,30,30,True
2018-07,895507.22,6273,7092,142.755814,31,31,True

In [137]:
complete_monthly_profile["revenue_change_pct"] = (
    complete_monthly_profile["revenue"]
    .pct_change()
    * 100
)

In [138]:
complete_monthly_profile[["revenue", "revenue_change_pct"]]

                   revenue  revenue_change_pct
purchase_month
2017-02          247303.02                 NaN
2017-03          374344.30           51.370695
2017-04          359927.23           -3.851286
2017-05          506071.14           40.603738
2017-06          433038.60          -14.431279
2017-07          498031.48           15.008565
2017-08          573971.68           15.248072
2017-09          624401.69            8.786150
2017-10          664219.43            6.376943
2017-11         1010271.37           52.099039
2017-12          743914.17          -26.364916
2018-01          950030.36           27.706985
2018-02          844178.71          -11.141923
2018-03          983213.44           16.469822
2018-04          996647.75            1.366368
2018-05          996517.68           -0.013051
2018-06          865124.31          -13.185252
2018-07          895507.22            3.511970

Há sinais de deterioração do desempenho de vendas no período mais recente observado, mas a série apresenta oscilações e não sustenta, por si só, a conclusão de uma queda contínua.

In [139]:
complete_monthly_profile["orders_change_pct"] = (
    complete_monthly_profile["orders"]
    .pct_change()
    * 100
)

In [140]:
complete_monthly_profile[[
    "revenue",
    "revenue_change_pct",
    "orders",
    "orders_change_pct"
]]

                   revenue  revenue_change_pct  orders  orders_change_pct
purchase_month
2017-02          247303.02                 NaN    1733                NaN
2017-03          374344.30           51.370695    2641          52.394691
2017-04          359927.23           -3.851286    2391          -9.466111
2017-05          506071.14           40.603738    3660          53.074028
2017-06          433038.60          -14.431279    3217         -12.103825
2017-07          498031.48           15.008565    3969          23.375816
2017-08          573971.68           15.248072    4293           8.163265
2017-09          624401.69            8.786150    4243          -1.164687
2017-10          664219.43            6.376943    4568           7.659675
2017-11         1010271.37           52.099039    7451          63.112960
2017-12          743914.17          -26.364916    5624         -24.520199
2018-01          950030.36           27.706985    7220          28.378378
2018-02          844178.71          -11.141923    6694          -7.285319
2018-03          983213.44           16.469822    7188           7.379743
2018-04          996647.75            1.366368    6934          -3.533667
2018-05          996517.68           -0.013051    6853          -1.168157
2018-06          865124.31          -13.185252    6160         -10.112360
2018-07          895507.22            3.511970    6273           1.834416

In [141]:
complete_monthly_profile["ticket_change_pct"] = (
    complete_monthly_profile["ticket"].pct_change() * 100
)

In [142]:
complete_monthly_profile[[
    "revenue",
    "revenue_change_pct",
    "orders",
    "orders_change_pct",
    "ticket",
    "ticket_change_pct"
]]

,revenue,revenue_change_pct,orders,orders_change_pct,ticket,ticket_change_pct
purchase_month,,,,,,
2017-02,247303.02,NaN,1733,NaN,142.702262,NaN
2017-03,374344.30,51.370695,2641,52.394691,141.743393,-0.671937
2017-04,359927.23,-3.851286,2391,-9.466111,150.534182,6.201904
2017-05,506071.14,40.603738,3660,53.074028,138.270803,-8.146574
2017-06,433038.60,-14.431279,3217,-12.103825,134.609450,-2.647958
2017-07,498031.48,15.008565,3969,23.375816,125.480343,-6.781921
2017-08,573971.68,15.248072,4293,8.163265,133.699436,6.550105
2017-09,624401.69,8.786150,4243,-1.164687,147.160427,10.068098
2017-10,664219.43,6.376943,4568,7.659675,145.407056,-1.191469
2017-11,1010271.37,52.099039,7451,63.112960,135.588695,-6.752327
2017-12,743914.17,-26.364916,5624,-24.520199,132.274924,-2.443988
2018-01,950030.36,27.706985,7220,28.378378,131.583152,-0.522980
2018-02,844178.71,-11.141923,6694,-7.285319,126.109756,-4.159648
2018-03,983213.44,16.469822,7188,7.379743,136.785398,8.465357
2018-04,996647.75,1.366368,6934,-3.533667,143.733451,5.079528
2018-05,996517.68,-0.013051,6853,-1.168157,145.413349,1.168759
2018-06,865124.31,-13.185252,6160,-10.112360,140.442258,-3.418593
2018-07,895507.22,3.511970,6273,1.834416,142.755814,1.647336

Entre maio e junho de 2018, a receita de produtos apresentou queda de 13,19%, acompanhada por redução de 10,11% no número de pedidos e de 3,42% no ticket médio.

O desempenho de vendas apresenta oscilações relevantes ao longo do período, com episódios de retração da receita associados a diferentes combinações entre volume de pedidos e ticket médio. O período de maio para junho de 2018 apresenta uma queda de 13,19% na receita, acompanhada simultaneamente por redução no volume de pedidos e no ticket médio.

In [143]:
complete_monthly_profile["revenue_check"] = (
    complete_monthly_profile["orders"]
    * complete_monthly_profile["ticket"]
)

complete_monthly_profile[[
    "revenue",
    "orders",
    "ticket",
    "revenue_check"
]]

                   revenue  orders      ticket  revenue_check
purchase_month
2017-02          247303.02    1733  142.702262      247303.02
2017-03          374344.30    2641  141.743393      374344.30
2017-04          359927.23    2391  150.534182      359927.23
2017-05          506071.14    3660  138.270803      506071.14
2017-06          433038.60    3217  134.609450      433038.60
2017-07          498031.48    3969  125.480343      498031.48
2017-08          573971.68    4293  133.699436      573971.68
2017-09          624401.69    4243  147.160427      624401.69
2017-10          664219.43    4568  145.407056      664219.43
2017-11         1010271.37    7451  135.588695     1010271.37
2017-12          743914.17    5624  132.274924      743914.17
2018-01          950030.36    7220  131.583152      950030.36
2018-02          844178.71    6694  126.109756      844178.71
2018-03          983213.44    7188  136.785398      983213.44
2018-04          996647.75    6934  143.733451      996647.75
2018-05          996517.68    6853  145.413349      996517.68
2018-06          865124.31    6160  140.442258      865124.31
2018-07          895507.22    6273  142.755814      895507.22

In [144]:
products_path = "../data/raw/olist_products_dataset.csv"

products = pd.read_csv(products_path)

products.shape

(32951, 9)

In [145]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [146]:
products["product_id"].nunique()

32951

In [147]:
order_items["product_id"].isin(products["product_id"]).mean()

np.float64(1.0)

In [148]:
sales_base = sales_base.merge(
    products[
        [
            "product_id",
            "product_category_name"
        ]
    ],
    on="product_id",
    how="left"
)

In [149]:
sales_base.shape

(112650, 12)

In [150]:
sales_base.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value',
       'order_purchase_timestamp', 'order_status', 'purchase_month',
       'purchase_date', 'product_category_name'],
      dtype='str')

In [151]:
sales_base["product_category_name"].isna().sum()

np.int64(1603)

In [152]:
(
    sales_base["product_category_name"].isna().mean()
    * 100
)

np.float64(1.4229915667998225)

In [153]:
sales_base.loc[
    sales_base["product_category_name"].isna(),
    "price"
].sum()

np.float64(179535.28)

In [154]:
sales_base["price"].sum()

np.float64(13591643.7)

In [155]:
(
    sales_base.loc[
        sales_base["product_category_name"].isna(),
        "price"
    ].sum()
    / sales_base["price"].sum()
    * 100
)

np.float64(1.3209239733086882)

In [156]:
category_revenue = (
    sales_base
    .groupby("product_category_name", dropna=False)["price"]
    .sum()
    .sort_values(ascending=False)
)

category_revenue.head(10)

product_category_name
beleza_saude              1258681.34
relogios_presentes        1205005.68
cama_mesa_banho           1036988.68
esporte_lazer              988048.97
informatica_acessorios     911954.32
moveis_decoracao           729762.49
cool_stuff                 635290.85
utilidades_domesticas      632248.66
automotivo                 592720.11
ferramentas_jardim         485256.46
Name: price, dtype: float64

In [157]:
category_profile = (
    sales_base
    .groupby("product_category_name", dropna=False)
    .agg(
        revenue=("price", "sum"),
        orders=("order_id", "nunique")
    )
)

category_profile["ticket"] = (
    category_profile["revenue"]
    / category_profile["orders"]
)

category_profile.sort_values(
    "revenue",
    ascending=False
).head(10)

                           revenue  orders      ticket
product_category_name
beleza_saude            1258681.34    8836  142.449224
relogios_presentes      1205005.68    5624  214.261323
cama_mesa_banho         1036988.68    9417  110.118794
esporte_lazer            988048.97    7720  127.985618
informatica_acessorios   911954.32    6689  136.336421
moveis_decoracao         729762.49    6449  113.159015
cool_stuff               635290.85    3632  174.914882
utilidades_domesticas    632248.66    5884  107.452186
automotivo               592720.11    3897  152.096513
ferramentas_jardim       485256.46    3518  137.935321

In [158]:
category_profile["revenue_share_pct"] = (
    category_profile["revenue"]
    / sales_base["price"].sum()
    * 100
)

category_profile.sort_values(
    "revenue",
    ascending=False
).head(10)

                           revenue  orders      ticket  revenue_share_pct
product_category_name
beleza_saude            1258681.34    8836  142.449224           9.260700
relogios_presentes      1205005.68    5624  214.261323           8.865783
cama_mesa_banho         1036988.68    9417  110.118794           7.629605
esporte_lazer            988048.97    7720  127.985618           7.269533
informatica_acessorios   911954.32    6689  136.336421           6.709669
moveis_decoracao         729762.49    6449  113.159015           5.369200
cool_stuff               635290.85    3632  174.914882           4.674128
utilidades_domesticas    632248.66    5884  107.452186           4.651745
automotivo               592720.11    3897  152.096513           4.360916
ferramentas_jardim       485256.46    3518  137.935321           3.570256

In [159]:
category_monthly_revenue = (
    sales_base
    .groupby(
        ["purchase_month", "product_category_name"],
        dropna=False
    )["price"]
    .sum()
)

category_monthly_revenue.head(20)

purchase_month  product_category_name
2016-09         beleza_saude                    134.97
                moveis_decoracao                 72.89
                telefonia                        59.50
2016-10         alimentos                        79.90
                audio                           156.99
                automotivo                     1833.25
                bebes                          1630.16
                beleza_saude                   4552.51
                brinquedos                     4465.09
                cama_mesa_banho                 478.99
                climatizacao                   1707.09
                consoles_games                 3882.26
                cool_stuff                     1111.00
                eletronicos                    1306.99
                esporte_lazer                  3333.64
                fashion_bolsas_e_acessorios     508.30
                fashion_calcados                 29.99
                fashion_roupa_feminina           54.90
                fashion_roupa_masculina          24.90
                ferramentas_jardim             1359.88
Name: price, dtype: float64

In [160]:
category_monthly_revenue_complete = (
    category_monthly_revenue
    .loc[
        category_monthly_revenue.index.get_level_values("purchase_month")
        .isin(complete_monthly_profile.index)
    ]
    .unstack("product_category_name", fill_value=0)
)

category_monthly_revenue_complete.head()

product_category_name,agro_industria_e_comercio,alimentos,alimentos_bebidas,artes,artes_e_artesanato,artigos_de_festas,artigos_de_natal,audio,automotivo,bebes,...,portateis_casa_forno_e_cafe,portateis_cozinha_e_preparadores_de_alimentos,relogios_presentes,seguros_e_servicos,sinalizacao_e_seguranca,tablets_impressao_imagem,telefonia,telefonia_fixa,utilidades_domesticas,NaN
purchase_month,,,,,,,,,,,,,,,,,,,,,
2017-02,224.84,715.63,0.00,0.00,0.00,0.0,0.0,163.80,13162.40,3048.48,...,0.0,0.0,11756.21,0.0,0.00,792.00,6899.09,759.23,12659.67,9034.10
2017-03,81.99,2667.56,110.80,223.25,0.00,0.0,0.0,1134.77,14482.07,3724.08,...,0.0,0.0,26770.38,0.0,75.00,495.00,8121.05,1592.35,13511.81,6714.17
2017-04,0.00,491.30,47.90,119.90,0.00,0.0,69.0,942.20,15548.17,3980.45,...,0.0,0.0,23487.78,0.0,128.06,1112.88,7245.87,2998.33,15028.84,8693.09
2017-05,1579.94,387.90,416.29,6967.65,21.99,0.0,0.0,2081.18,18640.03,9849.51,...,0.0,0.0,37973.90,0.0,508.85,1514.98,9264.10,462.33,21726.48,10961.94
2017-06,1390.00,149.90,57.40,421.70,0.00,0.0,184.7,1671.00,31370.69,7864.74,...,71.9,0.0,28948.63,0.0,273.90,594.00,6757.62,933.67,23623.71,5527.79

In [161]:
category_change = (
    (
        category_monthly_revenue_complete.iloc[-1]
        - category_monthly_revenue_complete.iloc[0]
    )
    / category_monthly_revenue_complete.iloc[0]
    * 100
)

category_change.sort_values().head(10)

product_category_name
fashion_roupa_feminina           -100.000000
tablets_impressao_imagem         -100.000000
market_place                      -88.936276
fashion_underwear_e_moda_praia    -72.340479
fashion_roupa_masculina           -67.535195
NaN                               -48.948982
climatizacao                      -14.132394
moveis_escritorio                  16.680445
eletroportateis                    20.128993
moveis_sala                        78.805158
dtype: float64

In [162]:
category_revenue_change = (
    category_monthly_revenue_complete.iloc[-1]
    - category_monthly_revenue_complete.iloc[0]
)

category_revenue_change.sort_values().head(10)

product_category_name
NaN                              -4422.10
market_place                     -1501.44
tablets_impressao_imagem          -792.00
fashion_roupa_feminina            -457.80
climatizacao                      -437.44
fashion_roupa_masculina           -434.15
fashion_underwear_e_moda_praia    -287.17
cds_dvds_musicais                    0.00
fashion_esporte                      0.00
seguros_e_servicos                   0.00
dtype: float64

In [163]:
category_change_recent = (
    category_monthly_revenue_complete.loc["2018-06"]
    - category_monthly_revenue_complete.loc["2018-05"]
)

category_change_recent.sort_values().head(10)

product_category_name
relogios_presentes            -36987.10
ferramentas_jardim            -19844.47
esporte_lazer                 -13813.10
moveis_decoracao              -12070.76
cool_stuff                    -10722.74
brinquedos                    -10545.85
informatica_acessorios         -9189.28
moveis_escritorio              -8280.28
eletronicos                    -7324.72
portateis_casa_forno_e_cafe    -6662.60
dtype: float64

In [164]:
category_recent_profile = (
    sales_base[
        sales_base["purchase_month"].isin(
            [pd.Period("2018-05", freq="M"), pd.Period("2018-06", freq="M")]
        )
    ]
    .groupby(
        ["purchase_month", "product_category_name"],
        dropna=False
    )
    .agg(
        revenue=("price", "sum"),
        orders=("order_id", "nunique")
    )
)

category_recent_profile["ticket"] = (
    category_recent_profile["revenue"]
    / category_recent_profile["orders"]
)

category_recent_profile

                                           revenue  orders      ticket
purchase_month product_category_name
2018-05        agro_industria_e_comercio   3279.75       8  409.968750
               alimentos                   1542.93      36   42.859167
               alimentos_bebidas           1239.44      15   82.629333
               artes                       2691.86      35   76.910286
               artes_e_artesanato            89.80       1   89.800000
...                                            ...     ...         ...
2018-06        tablets_impressao_imagem      50.00       1   50.000000
               telefonia                  22776.82     205  111.106439
               telefonia_fixa              2080.32      15  138.688000
               utilidades_domesticas      56825.45     470  120.905213
               NaN                         2387.13      22  108.505909

[130 rows x 3 columns]

In [165]:
relogios_recent = (
    category_recent_profile
    .loc[
        category_recent_profile.index.get_level_values("product_category_name")
        == "relogios_presentes"
    ]
    .copy()
)

relogios_recent

                                        revenue  orders      ticket
purchase_month product_category_name
2018-05        relogios_presentes     123872.66     596  207.840034
2018-06        relogios_presentes      86885.56     448  193.940982

In [166]:
relogios_change = (
    relogios_recent
    .iloc[1]
    .loc[["revenue", "orders", "ticket"]]
    / relogios_recent
    .iloc[0]
    .loc[["revenue", "orders", "ticket"]]
    - 1
) * 100

relogios_change

revenue   -29.858970
orders    -24.832215
ticket     -6.687379
dtype: float64

In [167]:
top_categories = (
    category_change_recent
    .sort_values()
    .head(10)
    .index
)

category_priority_profile = (
    category_recent_profile
    .loc[
        category_recent_profile.index.get_level_values("product_category_name")
        .isin(top_categories)
    ]
    .copy()
)

category_priority_profile

                                              revenue  orders       ticket
purchase_month product_category_name
2018-05        brinquedos                    31767.30     214   148.445327
               cool_stuff                    30039.11     169   177.746213
               eletronicos                   16989.29     223    76.185157
               esporte_lazer                 59664.11     452   132.000243
               ferramentas_jardim            37863.18     230   164.622522
               informatica_acessorios        51515.73     409   125.955330
               moveis_decoracao              54260.98     462   117.448009
               moveis_escritorio             21005.86      83   253.082651
               portateis_casa_forno_e_cafe   10161.60       9  1129.066667
               relogios_presentes           123872.66     596   207.840034
2018-06        brinquedos                    21221.45     177   119.895198
               cool_stuff                    19316.37     100   193.163700
               eletronicos                    9664.57     174    55.543506
               esporte_lazer                 45851.01     377   121.620716
               ferramentas_jardim            18018.71     149   120.930940
               informatica_acessorios        42326.45     358   118.230307
               moveis_decoracao              42190.22     318   132.673648
               moveis_escritorio             12725.58      60   212.093000
               portateis_casa_forno_e_cafe    3499.00       3  1166.333333
               relogios_presentes            86885.56     448   193.940982

In [168]:
category_priority_comparison = (
    category_priority_profile
    .reset_index()
    .pivot(
        index="product_category_name",
        columns="purchase_month",
        values=["revenue", "orders", "ticket"]
    )
)

category_priority_comparison

                               revenue            orders               ticket  \
purchase_month                 2018-05   2018-06 2018-05 2018-06      2018-05
product_category_name
brinquedos                    31767.30  21221.45   214.0   177.0   148.445327
cool_stuff                    30039.11  19316.37   169.0   100.0   177.746213
eletronicos                   16989.29   9664.57   223.0   174.0    76.185157
esporte_lazer                 59664.11  45851.01   452.0   377.0   132.000243
ferramentas_jardim            37863.18  18018.71   230.0   149.0   164.622522
informatica_acessorios        51515.73  42326.45   409.0   358.0   125.955330
moveis_decoracao              54260.98  42190.22   462.0   318.0   117.448009
moveis_escritorio             21005.86  12725.58    83.0    60.0   253.082651
portateis_casa_forno_e_cafe   10161.60   3499.00     9.0     3.0  1129.066667
relogios_presentes           123872.66  86885.56   596.0   448.0   207.840034


purchase_month                   2018-06
product_category_name
brinquedos                    119.895198
cool_stuff                    193.163700
eletronicos                    55.543506
esporte_lazer                 121.620716
ferramentas_jardim            120.930940
informatica_acessorios        118.230307
moveis_decoracao              132.673648
moveis_escritorio             212.093000
portateis_casa_forno_e_cafe  1166.333333
relogios_presentes            193.940982

In [169]:
category_priority_change = pd.DataFrame({
    "revenue_change_pct": (
        (
            category_priority_comparison["revenue"]["2018-06"]
            / category_priority_comparison["revenue"]["2018-05"]
        ) - 1
    ) * 100,
    
    "orders_change_pct": (
        (
            category_priority_comparison["orders"]["2018-06"]
            / category_priority_comparison["orders"]["2018-05"]
        ) - 1
    ) * 100,
    
    "ticket_change_pct": (
        (
            category_priority_comparison["ticket"]["2018-06"]
            / category_priority_comparison["ticket"]["2018-05"]
        ) - 1
    ) * 100
})

category_priority_change

,revenue_change_pct,orders_change_pct,ticket_change_pct
product_category_name,,,
brinquedos,-33.197187,-17.289720,-19.232757
cool_stuff,-35.695931,-40.828402,8.673876
eletronicos,-43.113750,-21.973094,-27.094059
esporte_lazer,-23.151439,-16.592920,-7.863264
ferramentas_jardim,-52.410997,-35.217391,-26.540465
informatica_acessorios,-17.837814,-12.469438,-6.133145
moveis_decoracao,-22.245746,-31.168831,12.963727
moveis_escritorio,-39.418905,-27.710843,-16.196152
portateis_casa_forno_e_cafe,-65.566446,-66.666667,3.300661
relogios_presentes,-29.858970,-24.832215,-6.687379

In [170]:
category_priority_change["revenue_change_abs"] = (
    category_priority_comparison["revenue"]["2018-06"]
    - category_priority_comparison["revenue"]["2018-05"]
)

category_priority_change.sort_values(
    "revenue_change_abs"
)

,revenue_change_pct,orders_change_pct,ticket_change_pct,revenue_change_abs
product_category_name,,,,
relogios_presentes,-29.858970,-24.832215,-6.687379,-36987.10
ferramentas_jardim,-52.410997,-35.217391,-26.540465,-19844.47
esporte_lazer,-23.151439,-16.592920,-7.863264,-13813.10
moveis_decoracao,-22.245746,-31.168831,12.963727,-12070.76
cool_stuff,-35.695931,-40.828402,8.673876,-10722.74
brinquedos,-33.197187,-17.289720,-19.232757,-10545.85
informatica_acessorios,-17.837814,-12.469438,-6.133145,-9189.28
moveis_escritorio,-39.418905,-27.710843,-16.196152,-8280.28
eletronicos,-43.113750,-21.973094,-27.094059,-7324.72
portateis_casa_forno_e_cafe,-65.566446,-66.666667,3.300661,-6662.60

In [171]:
total_revenue_change = (
    complete_monthly_profile.loc["2018-06", "revenue"]
    - complete_monthly_profile.loc["2018-05", "revenue"]
)

top_10_revenue_change = category_priority_change["revenue_change_abs"].sum()

coverage_of_revenue_decline = (
    top_10_revenue_change / total_revenue_change
) * 100

total_revenue_change, top_10_revenue_change, coverage_of_revenue_decline

(np.float64(-131393.37),
 np.float64(-135440.90000000002),
 np.float64(103.080467454332))

In [172]:
category_change_all = (
    category_monthly_revenue_complete.iloc[-1]
    - category_monthly_revenue_complete.iloc[0]
)

category_change_all.sort_values()

product_category_name
NaN                         -4422.10
market_place                -1501.44
tablets_impressao_imagem     -792.00
fashion_roupa_feminina       -457.80
climatizacao                 -437.44
                              ...
cama_mesa_banho             38800.09
esporte_lazer               38920.52
utilidades_domesticas       50749.47
beleza_saude                82974.24
relogios_presentes          84456.38
Length: 74, dtype: float64

In [173]:
category_priority_monthly = (
    category_monthly_revenue_complete[
        top_categories
    ]
)

category_priority_monthly

product_category_name,relogios_presentes,ferramentas_jardim,esporte_lazer,moveis_decoracao,cool_stuff,brinquedos,informatica_acessorios,moveis_escritorio,eletronicos,portateis_casa_forno_e_cafe
purchase_month,,,,,,,,,,
2017-02,11756.21,13144.61,16372.16,20986.10,13323.60,9403.34,11972.59,11805.98,1218.85,0.00
2017-03,26770.38,23747.15,27001.59,23477.63,21095.21,12429.47,28624.60,11783.51,3986.00,0.00
2017-04,23487.78,20809.28,24864.33,21690.42,21822.08,13039.43,20691.06,9411.30,4822.24,0.00
2017-05,37973.90,20693.46,36163.50,24028.51,33696.47,22626.95,45634.78,8403.43,6709.11,0.00
2017-06,28948.63,15851.17,32898.33,16943.58,38244.50,15476.35,37007.08,7279.13,2100.04,71.90
2017-07,36804.56,20067.05,38813.41,24751.92,37506.76,24511.72,38709.00,16892.61,7346.84,0.00
2017-08,36419.20,24269.40,41732.26,35511.73,41720.03,18126.87,35025.72,9877.36,2854.15,109.06
2017-09,47135.60,22507.23,50167.48,30838.69,38210.34,31399.22,28930.98,9208.65,4338.96,640.99
2017-10,65959.53,25978.74,49751.45,30227.51,44910.01,34633.01,44022.09,17890.83,3454.32,0.00
2017-11,97724.57,45972.18,64874.05,63223.97,56295.24,64320.89,72656.00,18048.20,10026.14,0.00
2017-12,71727.62,27689.69,59792.66,32011.75,39011.54,57194.14,37880.65,6964.36,8537.51,0.00
2018-01,75621.24,27037.94,91574.33,55438.18,39739.70,21948.23,83257.45,20113.41,15996.68,369.99
2018-02,63462.18,26838.03,75863.95,38646.52,31002.21,14778.93,100855.23,17774.78,14780.60,3024.90
2018-03,97861.08,27612.25,85292.17,52244.04,38353.22,23407.40,85673.53,31301.62,12554.80,7890.90
2018-04,92658.57,35037.64,67528.08,56793.01,35202.40,23352.38,59651.20,20194.72,11022.43,13980.98
2018-05,123872.66,37863.18,59664.11,54260.98,30039.11,31767.30,51515.73,21005.86,16989.29,10161.60
2018-06,86885.56,18018.71,45851.01,42190.22,19316.37,21221.45,42326.45,12725.58,9664.57,3499.00
2018-07,96212.59,26173.78,55292.68,45715.49,30551.61,17277.29,41902.79,13775.27,11150.75,4699.67

In [174]:
revenue_check_2018_05 = (
    category_priority_comparison["orders"]["2018-05"]
    * category_priority_comparison["ticket"]["2018-05"]
)

revenue_check_2018_05

product_category_name
brinquedos                      31767.30
cool_stuff                      30039.11
eletronicos                     16989.29
esporte_lazer                   59664.11
ferramentas_jardim              37863.18
informatica_acessorios          51515.73
moveis_decoracao                54260.98
moveis_escritorio               21005.86
portateis_casa_forno_e_cafe     10161.60
relogios_presentes             123872.66
Name: 2018-05, dtype: float64

In [175]:
revenue_check_2018_06 = (
    category_priority_comparison["orders"]["2018-06"]
    * category_priority_comparison["ticket"]["2018-06"]
)

revenue_check_2018_06

product_category_name
brinquedos                     21221.45
cool_stuff                     19316.37
eletronicos                     9664.57
esporte_lazer                  45851.01
ferramentas_jardim             18018.71
informatica_acessorios         42326.45
moveis_decoracao               42190.22
moveis_escritorio              12725.58
portateis_casa_forno_e_cafe     3499.00
relogios_presentes             86885.56
Name: 2018-06, dtype: float64

In [176]:
category_revenue_validation = pd.DataFrame({
    "revenue_2018_05": category_priority_comparison["revenue"]["2018-05"],
    "revenue_check_2018_05": revenue_check_2018_05,
    "revenue_2018_06": category_priority_comparison["revenue"]["2018-06"],
    "revenue_check_2018_06": revenue_check_2018_06
})

category_revenue_validation

,revenue_2018_05,revenue_check_2018_05,revenue_2018_06,revenue_check_2018_06
product_category_name,,,,
brinquedos,31767.30,31767.30,21221.45,21221.45
cool_stuff,30039.11,30039.11,19316.37,19316.37
eletronicos,16989.29,16989.29,9664.57,9664.57
esporte_lazer,59664.11,59664.11,45851.01,45851.01
ferramentas_jardim,37863.18,37863.18,18018.71,18018.71
informatica_acessorios,51515.73,51515.73,42326.45,42326.45
moveis_decoracao,54260.98,54260.98,42190.22,42190.22
moveis_escritorio,21005.86,21005.86,12725.58,12725.58
portateis_casa_forno_e_cafe,10161.60,10161.60,3499.00,3499.00
relogios_presentes,123872.66,123872.66,86885.56,86885.56

# Consolidação do Data Profiling

## Principais achados

A análise do desempenho mensal mostrou que a receita apresenta comportamento oscilatório ao longo do período observado, não sendo identificada uma trajetória de queda contínua.

Considerando os meses completos e o período mais recente de maio para junho de 2018, observou-se:

- redução de 13,19% na receita;
- redução de 10,11% no número de pedidos;
- redução de 3,42% no ticket médio.

A decomposição da receita foi validada matematicamente por meio da relação:

**Receita = Pedidos × Ticket médio**

A validação foi realizada tanto para o desempenho agregado quanto para as categorias prioritárias analisadas.

## Comportamento por categoria

A análise das categorias mostrou que a deterioração recente não ocorreu de maneira uniforme.

Entre as categorias selecionadas pelas maiores perdas absolutas de receita entre maio e junho de 2018:

- `relogios_presentes` apresentou a maior redução absoluta, de R$ 36.987,10;
- `ferramentas_jardim` apresentou redução de R$ 19.844,47;
- `esporte_lazer` apresentou redução de R$ 13.813,10;
- `moveis_decoracao` apresentou redução de R$ 12.070,76;
- `cool_stuff` apresentou redução de R$ 10.722,74.

A decomposição por pedidos e ticket mostrou mecanismos diferentes entre as categorias. Em algumas delas, a redução da receita ocorreu acompanhada por queda simultânea no número de pedidos e no ticket médio. Em outras, o ticket médio aumentou enquanto o número de pedidos caiu.

Esse comportamento indica que a deterioração da receita não deve ser analisada exclusivamente pelo ticket médio ou exclusivamente pelo volume de pedidos.

## Compensação entre categorias

As dez categorias selecionadas apresentaram, em conjunto, redução de R$ 135.440,90 entre maio e junho de 2018, enquanto a queda líquida da receita total da operação foi de R$ 131.393,37.

A diferença indica que outras categorias apresentaram crescimento no mesmo período, compensando parcialmente parte das perdas observadas nas categorias selecionadas.

Portanto, a deterioração recente não foi uniforme em todo o portfólio de categorias.

## Limitações e cuidados de interpretação

Os meses de setembro de 2016 e setembro de 2018 possuem cobertura parcial e não foram utilizados na análise comparativa principal.

A comparação de maio para junho de 2018 representa um recorte recente de deterioração e não deve ser interpretada, isoladamente, como evidência de uma tendência estrutural de queda.

Além disso, grandes variações percentuais podem ocorrer em categorias com baixo volume de vendas. Por esse motivo, a priorização considerou conjuntamente variação percentual, impacto financeiro absoluto e comportamento de pedidos e ticket.

Os resultados desta etapa são descritivos. Não estabelecem causalidade.

## Hipóteses para a etapa de EDA

Com base nos achados do Data Profiling, a etapa seguinte deverá investigar:

1. se a deterioração recente está concentrada em determinados produtos dentro das categorias prioritárias;
2. se a redução do número de pedidos está concentrada em determinados produtos ou segmentos;
3. se determinados sellers apresentam comportamento associado à redução observada;
4. se a redução da receita está relacionada principalmente à quantidade de itens vendidos, ao ticket médio ou à combinação desses fatores em diferentes segmentos;
5. se existem padrões temporais ou de concentração que ajudem a explicar a deterioração observada.

Essas hipóteses serão investigadas na etapa de EDA e não constituem conclusões causais do Data Profiling.