O QUE EXISTE NESSA BASE DE DADOS?

In [1]:
from pathlib import Path

RAW_DIR = Path("../data/raw")

arquivos = sorted(RAW_DIR.glob("*.csv"))

for arquivo in arquivos:
    print(arquivo.name)

olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_orders_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv

In [2]:
import pandas as pd

tabelas = {}

for arquivo in arquivos:
    df = pd.read_csv(arquivo)
    tabelas[arquivo.stem] = df

In [3]:
print(f"Quantidade de tabelas carregadas: {len(tabelas)}")

for nome, df in tabelas.items():
    print(f"{nome}: {df.shape}")

Quantidade de tabelas carregadas: 9
olist_customers_dataset: (99441, 5)
olist_geolocation_dataset: (1000163, 5)
olist_order_items_dataset: (112650, 7)
olist_order_payments_dataset: (103886, 5)
olist_order_reviews_dataset: (99224, 7)
olist_orders_dataset: (99441, 8)
olist_products_dataset: (32951, 9)
olist_sellers_dataset: (3095, 4)
product_category_name_translation: (71, 2)

In [7]:
# Seleciona a tabela de clientes
df_customers = tabelas["olist_customers_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_customers_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_customers.shape[0]}")
print(f"Quantidade de colunas: {df_customers.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_customers.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_customers_dataset
======================================================================
Quantidade de linhas: 99441
Quantidade de colunas: 5

Colunas da tabela:
1. customer_id
2. customer_unique_id
3. customer_zip_code_prefix
4. customer_city
5. customer_state

In [8]:
# Seleciona a tabela de geolocalização
df_geolocation = tabelas["olist_geolocation_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_geolocation_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_geolocation.shape[0]}")
print(f"Quantidade de colunas: {df_geolocation.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_geolocation.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_geolocation_dataset
======================================================================
Quantidade de linhas: 1000163
Quantidade de colunas: 5

Colunas da tabela:
1. geolocation_zip_code_prefix
2. geolocation_lat
3. geolocation_lng
4. geolocation_city
5. geolocation_state

In [9]:
# Seleciona a tabela de itens dos pedidos
df_order_items = tabelas["olist_order_items_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_order_items_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_order_items.shape[0]}")
print(f"Quantidade de colunas: {df_order_items.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_order_items.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_order_items_dataset
======================================================================
Quantidade de linhas: 112650
Quantidade de colunas: 7

Colunas da tabela:
1. order_id
2. order_item_id
3. product_id
4. seller_id
5. shipping_limit_date
6. price
7. freight_value

In [10]:
# Seleciona a tabela de pagamentos dos pedidos
df_order_payments = tabelas["olist_order_payments_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_order_payments_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_order_payments.shape[0]}")
print(f"Quantidade de colunas: {df_order_payments.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_order_payments.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_order_payments_dataset
======================================================================
Quantidade de linhas: 103886
Quantidade de colunas: 5

Colunas da tabela:
1. order_id
2. payment_sequential
3. payment_type
4. payment_installments
5. payment_value

In [11]:
# Seleciona a tabela de avaliações dos pedidos
df_order_reviews = tabelas["olist_order_reviews_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_order_reviews_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_order_reviews.shape[0]}")
print(f"Quantidade de colunas: {df_order_reviews.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_order_reviews.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_order_reviews_dataset
======================================================================
Quantidade de linhas: 99224
Quantidade de colunas: 7

Colunas da tabela:
1. review_id
2. order_id
3. review_score
4. review_comment_title
5. review_comment_message
6. review_creation_date
7. review_answer_timestamp

In [12]:
# Seleciona a tabela de pedidos
df_orders = tabelas["olist_orders_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_orders_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_orders.shape[0]}")
print(f"Quantidade de colunas: {df_orders.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_orders.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_orders_dataset
======================================================================
Quantidade de linhas: 99441
Quantidade de colunas: 8

Colunas da tabela:
1. order_id
2. customer_id
3. order_status
4. order_purchase_timestamp
5. order_approved_at
6. order_delivered_carrier_date
7. order_delivered_customer_date
8. order_estimated_delivery_date

In [13]:
# Seleciona a tabela de produtos
df_products = tabelas["olist_products_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_products_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_products.shape[0]}")
print(f"Quantidade de colunas: {df_products.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_products.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_products_dataset
======================================================================
Quantidade de linhas: 32951
Quantidade de colunas: 9

Colunas da tabela:
1. product_id
2. product_category_name
3. product_name_lenght
4. product_description_lenght
5. product_photos_qty
6. product_weight_g
7. product_length_cm
8. product_height_cm
9. product_width_cm

In [14]:
# Seleciona a tabela de vendedores
df_sellers = tabelas["olist_sellers_dataset"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: olist_sellers_dataset")
print("=" * 70)

print(f"Quantidade de linhas: {df_sellers.shape[0]}")
print(f"Quantidade de colunas: {df_sellers.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_sellers.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: olist_sellers_dataset
======================================================================
Quantidade de linhas: 3095
Quantidade de colunas: 4

Colunas da tabela:
1. seller_id
2. seller_zip_code_prefix
3. seller_city
4. seller_state

In [15]:
# Seleciona a tabela de tradução das categorias
df_category_translation = tabelas["product_category_name_translation"]

# Mostra informações básicas da tabela
print("=" * 70)
print("TABELA: product_category_name_translation")
print("=" * 70)

print(f"Quantidade de linhas: {df_category_translation.shape[0]}")
print(f"Quantidade de colunas: {df_category_translation.shape[1]}")

print("\nColunas da tabela:")

for numero, coluna in enumerate(df_category_translation.columns, start=1):
    print(f"{numero}. {coluna}")

======================================================================
TABELA: product_category_name_translation
======================================================================
Quantidade de linhas: 71
Quantidade de colunas: 2

Colunas da tabela:
1. product_category_name
2. product_category_name_english

## Data Discovery — orders

### Objetivo

Validar a granularidade da tabela `olist_orders_dataset` e investigar a unicidade de `order_id`.

### Hipótese inicial

- Uma linha representa um pedido.
- `order_id` funciona como identificador do pedido.

In [16]:
df_orders = tabelas["olist_orders_dataset"]

print("Tabela:", "olist_orders_dataset")
print("Linhas:", df_orders.shape[0])
print("Colunas:", df_orders.shape[1])

print("\nQuantidade de order_id únicos:", df_orders["order_id"].nunique())

print("Quantidade de order_id nulos:", df_orders["order_id"].isna().sum())

print("Quantidade total de linhas:", len(df_orders))

Tabela: olist_orders_dataset
Linhas: 99441
Colunas: 8

Quantidade de order_id únicos: 99441
Quantidade de order_id nulos: 0
Quantidade total de linhas: 99441

In [17]:
print("Colunas da tabela orders:\n")

for numero, coluna in enumerate(df_orders.columns, start=1):
    print(f"{numero}. {coluna}")

Colunas da tabela orders:

1. order_id
2. customer_id
3. order_status
4. order_purchase_timestamp
5. order_approved_at
6. order_delivered_carrier_date
7. order_delivered_customer_date
8. order_estimated_delivery_date

In [18]:
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [20]:
df_customers = tabelas["olist_customers_dataset"]

print("Linhas em customers:", len(df_customers))
print("customer_id únicos:", df_customers["customer_id"].nunique())
print("customer_id nulos:", df_customers["customer_id"].isna().sum())

Linhas em customers: 99441
customer_id únicos: 99441
customer_id nulos: 0

In [21]:
customer_ids_orders = df_orders["customer_id"]

print("Clientes distintos em orders:", customer_ids_orders.nunique())
print("Clientes nulos em orders:", customer_ids_orders.isna().sum())

Clientes distintos em orders: 99441
Clientes nulos em orders: 0

In [22]:
customer_ids_orders = set(df_orders["customer_id"])
customer_ids_customers = set(df_customers["customer_id"])

clientes_orders_sem_cadastro = customer_ids_orders - customer_ids_customers

print(
    "customer_id de orders sem correspondência em customers:",
    len(clientes_orders_sem_cadastro)
)

customer_id de orders sem correspondência em customers: 0

In [23]:
clientes_customers_sem_pedido = (
    customer_ids_customers - customer_ids_orders
)

print(
    "customer_id de customers sem correspondência em orders:",
    len(clientes_customers_sem_pedido)
)

customer_id de customers sem correspondência em orders: 0

In [24]:
customer_orders_frequency = df_orders["customer_id"].value_counts()

print("Distribuição da quantidade de pedidos por customer_id:")
print(customer_orders_frequency.value_counts().sort_index())

print(
    "\nMaior número de pedidos associado a um único customer_id:",
    customer_orders_frequency.max()
)

Distribuição da quantidade de pedidos por customer_id:
count
1    99441
Name: count, dtype: int64

Maior número de pedidos associado a um único customer_id: 1

In [25]:
print(
    "customer_unique_id únicos:",
    df_customers["customer_unique_id"].nunique()
)

print(
    "customer_unique_id nulos:",
    df_customers["customer_unique_id"].isna().sum()
)

customer_unique_id únicos: 96096
customer_unique_id nulos: 0

In [26]:
unique_customer_frequency = df_customers["customer_unique_id"].value_counts()

print(
    "Clientes com mais de um customer_id:",
    (unique_customer_frequency > 1).sum()
)

print(
    "Maior quantidade de customer_id para um único customer_unique_id:",
    unique_customer_frequency.max()
)

Clientes com mais de um customer_id: 2997
Maior quantidade de customer_id para um único customer_unique_id: 17

In [27]:
print("Estados distintos:", df_customers["customer_state"].nunique())
print("Cidades distintas:", df_customers["customer_city"].nunique())
print("CEPs distintos:", df_customers["customer_zip_code_prefix"].nunique())

Estados distintos: 27
Cidades distintas: 4119
CEPs distintos: 14994

In [28]:
df_items = tabelas["olist_order_items_dataset"]

print("Tabela:", "olist_order_items_dataset")
print("Linhas:", df_items.shape[0])
print("Colunas:", df_items.shape[1])

print(
    "\nQuantidade de order_id únicos:",
    df_items["order_id"].nunique()
)

print(
    "Quantidade de order_id nulos:",
    df_items["order_id"].isna().sum()
)

Tabela: olist_order_items_dataset
Linhas: 112650
Colunas: 7

Quantidade de order_id únicos: 98666
Quantidade de order_id nulos: 0

In [29]:
print(
    "order_item_id únicos:",
    df_items["order_item_id"].nunique()
)

print(
    "order_item_id nulos:",
    df_items["order_item_id"].isna().sum()
)

print(
    "Duplicidades em (order_id, order_item_id):",
    df_items[["order_id", "order_item_id"]].duplicated().sum()
)

order_item_id únicos: 21
order_item_id nulos: 0
Duplicidades em (order_id, order_item_id): 0

In [30]:
order_ids_orders = set(df_orders["order_id"])
order_ids_items = set(df_items["order_id"])

print(
    "order_id em order_items sem correspondência em orders:",
    len(order_ids_items - order_ids_orders)
)

print(
    "order_id em orders sem correspondência em order_items:",
    len(order_ids_orders - order_ids_items)
)

order_id em order_items sem correspondência em orders: 0
order_id em orders sem correspondência em order_items: 775

In [31]:
orders_sem_itens = df_orders[
    ~df_orders["order_id"].isin(df_items["order_id"])
]

print(
    "Quantidade de pedidos sem itens:",
    len(orders_sem_itens)
)

print("\nDistribuição por status:")
print(
    orders_sem_itens["order_status"]
    .value_counts()
)

Quantidade de pedidos sem itens: 775

Distribuição por status:
order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [32]:
print("Nulos por coluna:")

print(
    df_items[
        [
            "product_id",
            "seller_id",
            "shipping_limit_date",
            "price",
            "freight_value"
        ]
    ].isna().sum()
)

Nulos por coluna:
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [33]:
df_products = tabelas["olist_products_dataset"]

product_ids_items = set(df_items["product_id"])
product_ids_products = set(df_products["product_id"])

print(
    "product_id em order_items sem correspondência em products:",
    len(product_ids_items - product_ids_products)
)

print(
    "product_id em products sem ocorrência em order_items:",
    len(product_ids_products - product_ids_items)
)

product_id em order_items sem correspondência em products: 0
product_id em products sem ocorrência em order_items: 0

In [34]:
df_sellers = tabelas["olist_sellers_dataset"]

print("Linhas em sellers:", len(df_sellers))
print(
    "seller_id únicos:",
    df_sellers["seller_id"].nunique()
)
print(
    "seller_id nulos:",
    df_sellers["seller_id"].isna().sum()
)

Linhas em sellers: 3095
seller_id únicos: 3095
seller_id nulos: 0

In [35]:
seller_ids_items = set(df_items["seller_id"])
seller_ids_sellers = set(df_sellers["seller_id"])

print(
    "seller_id em order_items sem correspondência em sellers:",
    len(seller_ids_items - seller_ids_sellers)
)

print(
    "seller_id em sellers sem ocorrência em order_items:",
    len(seller_ids_sellers - seller_ids_items)
)

seller_id em order_items sem correspondência em sellers: 0
seller_id em sellers sem ocorrência em order_items: 0

In [36]:
df_payments = tabelas["olist_order_payments_dataset"]

print("Tabela:", "olist_order_payments_dataset")
print("Linhas:", df_payments.shape[0])
print("Colunas:", df_payments.shape[1])

print(
    "\nQuantidade de order_id únicos:",
    df_payments["order_id"].nunique()
)

print(
    "Quantidade de order_id nulos:",
    df_payments["order_id"].isna().sum()
)

Tabela: olist_order_payments_dataset
Linhas: 103886
Colunas: 5

Quantidade de order_id únicos: 99440
Quantidade de order_id nulos: 0

In [37]:
payment_frequency = df_payments["order_id"].value_counts()

print(
    "Pedidos com mais de um registro de pagamento:",
    (payment_frequency > 1).sum()
)

print(
    "Maior quantidade de registros de pagamento para um pedido:",
    payment_frequency.max()
)

Pedidos com mais de um registro de pagamento: 2961
Maior quantidade de registros de pagamento para um pedido: 29

In [38]:
print(
    "payment_sequential únicos:",
    df_payments["payment_sequential"].nunique()
)

print(
    "payment_sequential nulos:",
    df_payments["payment_sequential"].isna().sum()
)

print(
    "\nDistribuição dos valores de payment_sequential:"
)

print(
    df_payments["payment_sequential"]
    .value_counts()
    .sort_index()
)

payment_sequential únicos: 29
payment_sequential nulos: 0

Distribuição dos valores de payment_sequential:
payment_sequential
1     99360
2      3039
3       581
4       278
5       170
6       118
7        82
8        54
9        43
10       34
11       29
12       21
13       13
14       10
15        8
16        6
17        6
18        6
19        6
20        4
21        4
22        3
23        2
24        2
25        2
26        2
27        1
28        1
29        1
Name: count, dtype: int64

In [39]:
order_ids_payments = set(df_payments["order_id"])
order_ids_orders = set(df_orders["order_id"])

print(
    "order_id em order_payments sem correspondência em orders:",
    len(order_ids_payments - order_ids_orders)
)

print(
    "order_id em orders sem ocorrência em order_payments:",
    len(order_ids_orders - order_ids_payments)
)

order_id em order_payments sem correspondência em orders: 0
order_id em orders sem ocorrência em order_payments: 1

In [40]:
order_ids_payments = set(df_payments["order_id"])
order_ids_orders = set(df_orders["order_id"])

orders_sem_pagamento = order_ids_orders - order_ids_payments

print("Quantidade de pedidos sem pagamento:", len(orders_sem_pagamento))
print("Pedido(s):", orders_sem_pagamento)

Quantidade de pedidos sem pagamento: 1
Pedido(s): {'bfbd0f9bdef84302105ad712db648a6c'}

In [41]:
df_orders[
    df_orders["order_id"] == "bfbd0f9bdef84302105ad712db648a6c"
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
30710,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00

In [42]:
df_items[
    df_items["order_id"] == "bfbd0f9bdef84302105ad712db648a6c"
]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
84389,bfbd0f9bdef84302105ad712db648a6c,1,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83
84390,bfbd0f9bdef84302105ad712db648a6c,2,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83
84391,bfbd0f9bdef84302105ad712db648a6c,3,5a6b04657a4c5ee34285d1e4619a96b4,ecccfa2bb93b34a3bf033cc5d1dcdc69,2016-09-19 23:11:33,44.99,2.83

In [44]:
df_reviews = tabelas["olist_order_reviews_dataset"]

In [45]:
print("Linhas:", len(df_reviews))
print("Colunas:", df_reviews.shape[1])
print("Colunas:", df_reviews.columns.tolist())

Linhas: 99224
Colunas: 7
Colunas: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

In [46]:
df_reviews[
    df_reviews["order_id"] == "bfbd0f9bdef84302105ad712db648a6c"
]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
37547,6916ca4502d6d3bfd39818759d55d536,bfbd0f9bdef84302105ad712db648a6c,1,NaN,nao recebi o produto e nem resposta da empresa,2016-10-06 00:00:00,2016-10-07 18:32:28

In [47]:
df_payments["payment_type"].value_counts(dropna=False)

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [48]:
df_payments[
    df_payments["payment_type"] == "not_defined"
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0

In [49]:
df_payments["payment_installments"].value_counts().sort_index()

payment_installments
0         2
1     52546
2     12413
3     10461
4      7098
5      5239
6      3920
7      1626
8      4268
9       644
10     5328
11       23
12      133
13       16
14       15
15       74
16        5
17        8
18       27
20       17
21        3
22        1
23        1
24       18
Name: count, dtype: int64

In [50]:
df_payments[
    df_payments["payment_installments"] == 0
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [51]:
df_payments[
    df_payments["order_id"].isin([
        "744bade1fcf9ff3f31d860ace076d422",
        "1a57108394169c0b47d8f876acc9ba2d"
    ])
].sort_values(["order_id", "payment_sequential"])

,order_id,payment_sequential,payment_type,payment_installments,payment_value
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69

In [54]:
df_orders[
    df_orders["order_id"].isin([
        "744bade1fcf9ff3f31d860ace076d422",
        "1a57108394169c0b47d8f876acc9ba2d"
    ])
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
63782,744bade1fcf9ff3f31d860ace076d422,5e5794daaa13f73e2f1cdb4114529843,delivered,2018-04-22 11:34:42,2018-04-24 19:04:46,2018-04-24 03:14:34,2018-04-27 20:55:28,2018-05-16 00:00:00
66368,1a57108394169c0b47d8f876acc9ba2d,48ebb06cf56dba9d009230cc751bb195,delivered,2018-05-15 16:25:14,2018-05-15 16:36:52,2018-05-17 12:37:00,2018-05-24 15:45:41,2018-06-06 00:00:00

In [55]:
df_items[
    df_items["order_id"].isin([
        "744bade1fcf9ff3f31d860ace076d422",
        "1a57108394169c0b47d8f876acc9ba2d"
    ])
].sort_values(["order_id", "order_item_id"])

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
11589,1a57108394169c0b47d8f876acc9ba2d,1,db35a562fb6ba63e19fa42a15349dc04,282f23a9769b2690c5dda22e316f9941,2018-05-18 16:31:54,41.69,23.28
11590,1a57108394169c0b47d8f876acc9ba2d,2,db35a562fb6ba63e19fa42a15349dc04,282f23a9769b2690c5dda22e316f9941,2018-05-18 16:31:54,41.69,23.28
51167,744bade1fcf9ff3f31d860ace076d422,1,0cf573090c66bb30ac5e53c82bdb0403,7202e2ba20579a9bd1acb29e61fe71f6,2018-04-26 12:31:06,45.90,12.79

In [56]:
totais_items = (
    df_items
    .groupby("order_id")
    .agg(
        valor_produtos=("price", "sum"),
        valor_frete=("freight_value", "sum")
    )
    .reset_index()
)

totais_items["valor_itens_frete"] = (
    totais_items["valor_produtos"] +
    totais_items["valor_frete"]
)

totais_items.head()

,order_id,valor_produtos,valor_frete,valor_itens_frete
0,00010242fe8c5a6d1ba2dd792cb16214,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,12.99,12.79,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,199.90,18.14,218.04

In [57]:
totais_payments = (
    df_payments
    .groupby("order_id")
    .agg(
        valor_pagamentos=("payment_value", "sum")
    )
    .reset_index()
)

totais_payments.head()

                           order_id  valor_pagamentos
0  00010242fe8c5a6d1ba2dd792cb16214             72.19
1  00018f77f2f0320c557190d7a144bdd3            259.83
2  000229ec398224ef6ca0657da4fc703e            216.87
3  00024acbcdf0a6daa1e931b038114c75             25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9            218.04

In [58]:
comparacao_valores = totais_items.merge(
    totais_payments,
    on="order_id",
    how="inner"
)

comparacao_valores.head()

,order_id,valor_produtos,valor_frete,valor_itens_frete,valor_pagamentos
0,00010242fe8c5a6d1ba2dd792cb16214,58.90,13.29,72.19,72.19
1,00018f77f2f0320c557190d7a144bdd3,239.90,19.93,259.83,259.83
2,000229ec398224ef6ca0657da4fc703e,199.00,17.87,216.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,12.99,12.79,25.78,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,199.90,18.14,218.04,218.04

In [59]:
comparacao_valores["diferenca"] = (
    comparacao_valores["valor_pagamentos"]
    - comparacao_valores["valor_itens_frete"]
)

comparacao_valores["diferenca"].describe()

count    98665.000000
mean         0.029092
std          1.129221
min        -51.620000
25%          0.000000
50%          0.000000
75%          0.000000
max        182.810000
Name: diferenca, dtype: float64

In [60]:
import numpy as np

comparacao_valores["corresponde"] = np.isclose(
    comparacao_valores["valor_pagamentos"],
    comparacao_valores["valor_itens_frete"],
    atol=0.01
)

comparacao_valores["corresponde"].value_counts()

corresponde
True     98365
False      300
Name: count, dtype: int64

In [61]:
divergencias = (
    comparacao_valores[
        ~comparacao_valores["corresponde"]
    ]
    .copy()
    .sort_values("diferenca")
)

divergencias[
    [
        "order_id",
        "valor_produtos",
        "valor_frete",
        "valor_itens_frete",
        "valor_pagamentos",
        "diferenca"
    ]
].head(10)

,order_id,valor_produtos,valor_frete,valor_itens_frete,valor_pagamentos,diferenca
14628,262118ce178bb3e4590a3adcf6d62e6b,119.80,57.94,177.74,126.12,-51.62
97605,fd33085945f15975375cd8ec85440511,217.99,16.63,234.62,212.82,-21.80
42504,6e57e23ecac1ae881286657694444267,330.00,20.41,350.41,333.91,-16.50
25102,4154bf1348caac78152fe76e3e9c4af8,149.90,15.36,165.26,150.27,-14.99
42292,6dcf0aeb8b1eb4021c26e1d0e9394979,299.00,34.92,333.92,318.97,-14.95
5533,0e556f5eafbf3eb399290101b183b10e,49.80,45.86,95.66,81.90,-13.76
49461,8092da256aefda13b330290d2ca86521,103.90,11.75,115.65,105.26,-10.39
65449,aa6bd33ba1853d846d3085a88ae37083,19.90,15.24,35.14,25.14,-10.00
25960,4387477eec4b3c89b39f3f454940d059,198.00,33.92,231.92,222.02,-9.90
76694,c6f6cbb3c845593222d5c594bb69c5fd,89.90,23.43,113.33,104.34,-8.99

In [62]:
pedido_teste = "262118ce178bb3e4590a3adcf6d62e6b"

print("=== PEDIDO ===")
print(
    df_orders[
        df_orders["order_id"] == pedido_teste
    ]
)

print("\n=== ITENS ===")
print(
    df_items[
        df_items["order_id"] == pedido_teste
    ]
)

print("\n=== PAGAMENTOS ===")
print(
    df_payments[
        df_payments["order_id"] == pedido_teste
    ]
)

=== PEDIDO ===
                               order_id                       customer_id  \
31661  262118ce178bb3e4590a3adcf6d62e6b  2a69da30b726b7f3db7f1059af5d4304

      order_status order_purchase_timestamp    order_approved_at  \
31661    delivered      2016-10-06 14:59:56  2016-10-07 12:13:49

      order_delivered_carrier_date order_delivered_customer_date  \
31661          2016-11-17 08:27:59           2016-11-17 16:23:46

      order_estimated_delivery_date
31661           2016-11-30 00:00:00

=== ITENS ===
                               order_id  order_item_id  \
16662  262118ce178bb3e4590a3adcf6d62e6b              1
16663  262118ce178bb3e4590a3adcf6d62e6b              2

                             product_id                         seller_id  \
16662  6aeed495dcb87dd06532f70dea6ebb5a  b56906f7fd1696e043f1bcce164c487b
16663  6aeed495dcb87dd06532f70dea6ebb5a  b56906f7fd1696e043f1bcce164c487b

       shipping_limit_date  price  freight_value
16662  2016-10-11 12:13:50   59.9          28.97
16663  2016-10-11 12:13:50   59.9          28.97

=== PAGAMENTOS ===
                               order_id  payment_sequential payment_type  \
85540  262118ce178bb3e4590a3adcf6d62e6b                   1  credit_card

       payment_installments  payment_value
85540                     5         126.12

In [63]:
divergencias["diferenca"].describe()

count    300.000000
mean       9.570000
std       18.142737
min      -51.620000
25%        1.550000
50%        5.425000
75%       11.925000
max      182.810000
Name: diferenca, dtype: float64

In [64]:
divergencias["diferenca"].value_counts().head(20)

diferenca
 0.02     12
-0.02     10
-0.02      3
 0.02      3
-0.02      2
 0.02      2
 0.03      2
 5.17      2
 5.27      2
 6.89      2
-51.62     1
-21.80     1
-16.50     1
-14.99     1
-14.95     1
-13.76     1
-10.39     1
-10.00     1
-9.90      1
-8.99      1
Name: count, dtype: int64

In [65]:
comparacao_valores["diferenca_abs"] = (
    comparacao_valores["diferenca"].abs()
)

comparacao_valores["categoria_divergencia"] = np.select(
    [
        comparacao_valores["diferenca_abs"] <= 0.05,
        comparacao_valores["diferenca_abs"] <= 10,
        comparacao_valores["diferenca_abs"] <= 50,
        comparacao_valores["diferenca_abs"] > 50
    ],
    [
        "Até R$ 0,05",
        "R$ 0,06 a R$ 10",
        "R$ 10,01 a R$ 50",
        "Acima de R$ 50"
    ],
    default="Sem divergência"
)

comparacao_valores["categoria_divergencia"].value_counts()

categoria_divergencia
Até R$ 0,05         98405
R$ 0,06 a R$ 10       162
R$ 10,01 a R$ 50       90
Acima de R$ 50          8
Name: count, dtype: int64

In [66]:
divergencias_extremas = (
    comparacao_valores[
        comparacao_valores["diferenca_abs"] > 50
    ]
    .sort_values("diferenca", ascending=False)
)

divergencias_extremas[
    [
        "order_id",
        "valor_produtos",
        "valor_frete",
        "valor_itens_frete",
        "valor_pagamentos",
        "diferenca"
    ]
]

,order_id,valor_produtos,valor_frete,valor_itens_frete,valor_pagamentos,diferenca
79537,ce6d150fb29ada17d2082f4847107665,1299.00,104.66,1403.66,1586.47,182.81
42515,6e5fe7366a2e1bfbf3257dba0af1267f,179.19,108.72,287.91,406.92,119.01
43434,70b742795bc441e94a44a084b6d9ce7a,269.99,196.94,466.93,578.82,111.89
58752,996c7e73600ad3723e8627ab7bef81e4,559.90,28.00,587.90,664.43,76.53
43437,70b7e94ea46d3e8b5bc12a50186edaf0,167.88,45.27,213.15,274.84,61.69
72496,bc2c82b0ef78d2252b6176d1972db7c9,165.00,77.01,242.01,303.02,61.01
67466,af9ffff2ce6b3defd34fd4c78857a379,395.65,17.52,413.17,466.97,53.80
14628,262118ce178bb3e4590a3adcf6d62e6b,119.80,57.94,177.74,126.12,-51.62

In [67]:
pedidos_extremos = divergencias_extremas["order_id"].tolist()

df_payments[
    df_payments["order_id"].isin(pedidos_extremos)
].sort_values(
    ["order_id", "payment_sequential"]
)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
85540,262118ce178bb3e4590a3adcf6d62e6b,1,credit_card,5,126.12
38060,6e5fe7366a2e1bfbf3257dba0af1267f,1,credit_card,10,406.92
25761,70b742795bc441e94a44a084b6d9ce7a,1,credit_card,20,578.82
2970,70b7e94ea46d3e8b5bc12a50186edaf0,1,credit_card,24,274.84
61856,996c7e73600ad3723e8627ab7bef81e4,1,credit_card,10,664.43
4954,af9ffff2ce6b3defd34fd4c78857a379,1,credit_card,10,466.97
27307,bc2c82b0ef78d2252b6176d1972db7c9,1,credit_card,21,303.02
359,ce6d150fb29ada17d2082f4847107665,1,credit_card,10,1586.47

In [68]:
df_items[
    df_items["order_id"].isin(pedidos_extremos)
].sort_values(
    ["order_id", "order_item_id"]
)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
16662,262118ce178bb3e4590a3adcf6d62e6b,1,6aeed495dcb87dd06532f70dea6ebb5a,b56906f7fd1696e043f1bcce164c487b,2016-10-11 12:13:50,59.90,28.97
16663,262118ce178bb3e4590a3adcf6d62e6b,2,6aeed495dcb87dd06532f70dea6ebb5a,b56906f7fd1696e043f1bcce164c487b,2016-10-11 12:13:50,59.90,28.97
48566,6e5fe7366a2e1bfbf3257dba0af1267f,1,7721582bb750762d81850267d19881c1,0c8380b62e38e8a1e6adbeba7eb9688c,2016-10-14 12:02:21,19.83,17.00
48567,6e5fe7366a2e1bfbf3257dba0af1267f,2,65bb78cf0bbc3ca6406f30e6793736f9,391fc6631aebcf3004804e51b40bcf1e,2016-10-14 12:02:20,39.90,19.24
48568,6e5fe7366a2e1bfbf3257dba0af1267f,3,7721582bb750762d81850267d19881c1,0c8380b62e38e8a1e6adbeba7eb9688c,2016-10-14 12:02:21,19.83,17.00
48569,6e5fe7366a2e1bfbf3257dba0af1267f,4,65bb78cf0bbc3ca6406f30e6793736f9,391fc6631aebcf3004804e51b40bcf1e,2016-10-14 12:02:20,39.90,19.24
48570,6e5fe7366a2e1bfbf3257dba0af1267f,5,7721582bb750762d81850267d19881c1,0c8380b62e38e8a1e6adbeba7eb9688c,2016-10-14 12:02:21,19.83,17.00
48571,6e5fe7366a2e1bfbf3257dba0af1267f,6,65bb78cf0bbc3ca6406f30e6793736f9,391fc6631aebcf3004804e51b40bcf1e,2016-10-14 12:02:20,39.90,19.24
49611,70b742795bc441e94a44a084b6d9ce7a,1,1dd284c37ca97cbb86c029c65fb9a494,070d165398b553f3b4b851c216b8a358,2017-08-30 10:35:22,269.99,196.94
49614,70b7e94ea46d3e8b5bc12a50186edaf0,1,59ebd2c07d59483d0855b5b3d5e18728,ea8482cd71df3c1969d7b9473ff13abc,2018-01-05 13:17:25,27.99,21.06
49615,70b7e94ea46d3e8b5bc12a50186edaf0,2,7ea0b63dc9b8264702f2d2c1533fb4ae,634964b17796e64304cadf1ad3050fb7,2018-01-05 13:17:25,69.90,21.06
49616,70b7e94ea46d3e8b5bc12a50186edaf0,3,c1eee16d856657ad280936810ef3d080,014d9a685fd57276679edd00e07089e5,2018-01-05 13:17:25,69.99,3.15
67125,996c7e73600ad3723e8627ab7bef81e4,1,1f2b3e5d739add9d4596ba6de24204d4,269cff2d3c8d205c11f37a52402ea93b,2018-07-20 10:10:18,559.90,28.00
77132,af9ffff2ce6b3defd34fd4c78857a379,1,e3dd336775af78a83fc27ed85f0f15da,edb1ef5e36e0c8cd84eb3c9b003e486d,2018-02-21 10:30:38,395.65,17.52
82859,bc2c82b0ef78d2252b6176d1972db7c9,1,423b46d7ff817b1cd19ab195c7b76546,6560211a19b47992c3666cc44a7e94c0,2017-11-22 12:56:23,55.00,25.67
82860,bc2c82b0ef78d2252b6176d1972db7c9,2,423b46d7ff817b1cd19ab195c7b76546,6560211a19b47992c3666cc44a7e94c0,2017-11-22 12:56:23,55.00,25.67
82861,bc2c82b0ef78d2252b6176d1972db7c9,3,423b46d7ff817b1cd19ab195c7b76546,6560211a19b47992c3666cc44a7e94c0,2017-11-22 12:56:23,55.00,25.67
90875,ce6d150fb29ada17d2082f4847107665,1,638bbb2a5e4f360b71f332ddfebfd672,c4af86330efa7a2620772227d2d670c9,2018-02-07 12:31:37,1299.00,104.66

In [69]:
divergencias_com_data = divergencias.merge(
    df_orders[
        [
            "order_id",
            "order_purchase_timestamp",
            "order_status"
        ]
    ],
    on="order_id",
    how="left"
)

divergencias_com_data[
    [
        "order_id",
        "order_purchase_timestamp",
        "order_status",
        "diferenca"
    ]
].sort_values("order_purchase_timestamp").head(20)

,order_id,order_purchase_timestamp,order_status,diferenca
0,262118ce178bb3e4590a3adcf6d62e6b,2016-10-06 14:59:56,delivered,-51.62
5,0e556f5eafbf3eb399290101b183b10e,2016-10-06 18:50:25,delivered,-13.76
189,06d7e8a85f5cfef576c5303ed7d7f2e5,2016-10-07 12:06:30,delivered,8.30
298,6e5fe7366a2e1bfbf3257dba0af1267f,2016-10-09 22:36:25,delivered,119.01
237,2f9d4ee8ca77fe0951ebfe9064cad953,2016-10-09 23:38:19,delivered,14.12
185,03b218d39c422c250f389120c531b61f,2017-01-14 14:20:01,delivered,7.79
123,d2e9aead95751dd6bd0ce80e7d506c53,2017-01-16 23:25:16,delivered,3.84
28,e09dd765041e9934d762d51ccb26adee,2017-01-21 06:58:31,delivered,-0.02
218,469f0b908881368c45917f1bed8240ce,2017-01-24 21:35:25,delivered,10.97
36,8adafb3466daa5395694d3a906ff9d40,2017-01-25 15:47:27,delivered,-0.02
274,a52e6fa2d7c6ecaf73ff5f7f10438339,2017-01-28 20:09:18,delivered,26.97
235,9224db86cedf958891e1b1afb4ad570c,2017-01-30 10:12:59,delivered,13.78
190,b05922c45fc699ae9049a2c5add3e02a,2017-02-02 07:05:42,delivered,8.47
70,c253cb678b5c3b8e8c9a13fc97d8e7f5,2017-02-06 14:31:27,delivered,1.24
244,971d58b94f7bda9a79f4847e1509a433,2017-02-07 23:16:34,delivered,16.22
78,6aaedd714ad6929fc4df8d51bd4cfe9a,2017-02-08 22:58:15,delivered,1.67
164,b495ec18170fb28a3610c8d3ab464442,2017-02-10 11:11:16,delivered,6.09
156,4d4aac37e91472a2cbb36ee91d35866f,2017-02-14 23:19:29,delivered,5.69
151,74016effecaa79d592487f6a4ee47d4b,2017-02-18 10:39:14,delivered,5.45
66,f090de1b2ed9f4e251662cb31e3c7127,2017-02-22 10:10:52,shipped,0.92

In [70]:
divergencias_com_pagamento = divergencias.merge(
    df_payments[
        [
            "order_id",
            "payment_type",
            "payment_installments",
            "payment_sequential",
            "payment_value"
        ]
    ],
    on="order_id",
    how="left"
)

divergencias_com_pagamento[
    "payment_type"
].value_counts(dropna=False)

payment_type
credit_card    290
boleto          13
debit_card       7
voucher          7
Name: count, dtype: int64

In [72]:
analise_pagamento = (
    comparacao_valores
    .merge(
        df_payments[
            ["order_id", "payment_type"]
        ].drop_duplicates("order_id"),
        on="order_id",
        how="left"
    )
    .groupby("payment_type")
    .agg(
        total_pedidos=("order_id", "count"),
        pedidos_com_divergencia=("corresponde", lambda x: (~x).sum())
    )
    .reset_index()
)

analise_pagamento["taxa_divergencia"] = (
    analise_pagamento["pedidos_com_divergencia"]
    / analise_pagamento["total_pedidos"]
    * 100
)

analise_pagamento.sort_values(
    "taxa_divergencia",
    ascending=False
)

  payment_type  total_pedidos  pedidos_com_divergencia  taxa_divergencia
2   debit_card           1520                        7          0.460526
1  credit_card          74883                      278          0.371246
3      voucher           2648                        2          0.075529
0       boleto          19614                       13          0.066279

A tabela order_payments possui granularidade de registro de pagamento, permitindo múltiplos registros por pedido. Embora a maior parte dos pedidos apresente compatibilidade entre o valor registrado nos pagamentos e a soma de produtos e frete, foram identificadas 300 divergências entre 98.665 pedidos comparáveis. As divergências estão distribuídas ao longo do período analisado e apresentam baixa frequência relativa entre os diferentes tipos de pagamento. Dessa forma, payment_value não será utilizado como fonte primária para o cálculo da receita de produtos no CASE 01. A receita de produtos será calculada a partir de order_items.price, enquanto payment_value será tratado como uma variável relacionada ao comportamento de pagamento.

In [73]:
df_products = tabelas["olist_products_dataset"]

print("Dimensões:", df_products.shape)
print("\nColunas:")
print(df_products.columns.tolist())

print("\nTipos:")
print(df_products.dtypes)

print("\nValores nulos:")
print(df_products.isna().sum())

print("\nProdutos únicos:")
print(df_products["product_id"].nunique())

print("\nLinhas duplicadas:")
print(df_products.duplicated().sum())

Dimensões: (32951, 9)

Colunas:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Tipos:
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

Valores nulos:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Produtos únicos:
32951

Linhas duplicadas:
0

In [74]:
produtos_nos_itens = set(df_items["product_id"].unique())
produtos_na_tabela = set(df_products["product_id"].unique())

itens_sem_produto = produtos_nos_itens - produtos_na_tabela
produtos_sem_vendas = produtos_na_tabela - produtos_nos_itens

print("Produtos presentes em order_items:", len(produtos_nos_itens))
print("Produtos presentes em products:", len(produtos_na_tabela))

print("\nProdutos vendidos que NÃO existem em products:",
      len(itens_sem_produto))

print("Produtos em products que NÃO aparecem em order_items:",
      len(produtos_sem_vendas))

Produtos presentes em order_items: 32951
Produtos presentes em products: 32951

Produtos vendidos que NÃO existem em products: 0
Produtos em products que NÃO aparecem em order_items: 0

In [75]:
print("Categorias únicas:", df_products["product_category_name"].nunique())

print("\nProdutos sem categoria:",
      df_products["product_category_name"].isna().sum())

print("\nCategorias com maior quantidade de produtos:")
print(
    df_products["product_category_name"]
    .value_counts(dropna=False)
    .head(20)
)

Categorias únicas: 73

Produtos sem categoria: 610

Categorias com maior quantidade de produtos:
product_category_name
cama_mesa_banho                      3029
esporte_lazer                        2867
moveis_decoracao                     2657
beleza_saude                         2444
utilidades_domesticas                2335
automotivo                           1900
informatica_acessorios               1639
brinquedos                           1411
relogios_presentes                   1329
telefonia                            1134
bebes                                 919
perfumaria                            868
papelaria                             849
fashion_bolsas_e_acessorios           849
cool_stuff                            789
ferramentas_jardim                    753
pet_shop                              719
NaN                                   610
eletronicos                           517
construcao_ferramentas_construcao     400
Name: count, dtype: int64

In [76]:
produtos_sem_categoria = df_products.loc[
    df_products["product_category_name"].isna(),
    "product_id"
]

itens_sem_categoria = df_items[
    df_items["product_id"].isin(produtos_sem_categoria)
]

print("Produtos sem categoria:", len(produtos_sem_categoria))

print(
    "Produtos sem categoria que aparecem em order_items:",
    itens_sem_categoria["product_id"].nunique()
)

print(
    "Linhas de venda relacionadas a produtos sem categoria:",
    len(itens_sem_categoria)
)

print(
    "Percentual das linhas de venda relacionadas a produtos sem categoria:",
    round(
        len(itens_sem_categoria) / len(df_items) * 100,
        2
    ),
    "%"
)

Produtos sem categoria: 610
Produtos sem categoria que aparecem em order_items: 610
Linhas de venda relacionadas a produtos sem categoria: 1603
Percentual das linhas de venda relacionadas a produtos sem categoria: 1.42 %

In [77]:
colunas_fisicas = [
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

print("Valores nulos:")
print(df_products[colunas_fisicas].isna().sum())

print("\nValores iguais a zero:")
print((df_products[colunas_fisicas] == 0).sum())

print("\nValores negativos:")
print((df_products[colunas_fisicas] < 0).sum())

Valores nulos:
product_weight_g     2
product_length_cm    2
product_height_cm    2
product_width_cm     2
dtype: int64

Valores iguais a zero:
product_weight_g     4
product_length_cm    0
product_height_cm    0
product_width_cm     0
dtype: int64

Valores negativos:
product_weight_g     0
product_length_cm    0
product_height_cm    0
product_width_cm     0
dtype: int64

In [78]:
produtos_com_problemas_fisicos = df_products[
    df_products[
        [
            "product_weight_g",
            "product_length_cm",
            "product_height_cm",
            "product_width_cm"
        ]
    ].isna().any(axis=1)
    |
    (df_products["product_weight_g"] == 0)
]

print(
    produtos_com_problemas_fisicos[
        [
            "product_id",
            "product_category_name",
            "product_weight_g",
            "product_length_cm",
            "product_height_cm",
            "product_width_cm"
        ]
    ]
)

                             product_id product_category_name  \
8578   09ff539a621711667c43eba6a3bd8466                 bebes
9769   81781c0fed9fe1ad6e8c81fca1e1cb08       cama_mesa_banho
13683  8038040ee2a71048d4bdbbdc985b69ab       cama_mesa_banho
14997  36ba42dd187055e1fbe943b2d11430ca       cama_mesa_banho
18851  5eb564652db742ff8f28759cd8d2652a                   NaN
32079  e673e90efa65a5409ff4196c038bb5af       cama_mesa_banho

       product_weight_g  product_length_cm  product_height_cm  \
8578                NaN                NaN                NaN
9769                0.0               30.0               25.0
13683               0.0               30.0               25.0
14997               0.0               30.0               25.0
18851               NaN                NaN                NaN
32079               0.0               30.0               25.0

       product_width_cm
8578                NaN
9769               30.0
13683              30.0
14997              30.0
18851               NaN
32079              30.0

In [79]:
ids_produtos_problema = produtos_com_problemas_fisicos["product_id"]

vendas_produtos_problema = df_items[
    df_items["product_id"].isin(ids_produtos_problema)
]

print(
    "Produtos com inconsistência física que possuem vendas:",
    vendas_produtos_problema["product_id"].nunique()
)

print(
    "Linhas de venda desses produtos:",
    len(vendas_produtos_problema)
)

print("\nVendas por produto:")
print(
    vendas_produtos_problema
    .groupby("product_id")
    .agg(
        linhas_venda=("product_id", "size"),
        quantidade_unidades=("order_item_id", "count"),
        receita_produtos=("price", "sum")
    )
    .sort_values("receita_produtos", ascending=False)
)

Produtos com inconsistência física que possuem vendas: 6
Linhas de venda desses produtos: 26

Vendas por produto:
                                  linhas_venda  quantidade_unidades  \
product_id
09ff539a621711667c43eba6a3bd8466             1                    1
5eb564652db742ff8f28759cd8d2652a            17                   17
e673e90efa65a5409ff4196c038bb5af             4                    4
36ba42dd187055e1fbe943b2d11430ca             2                    2
8038040ee2a71048d4bdbbdc985b69ab             1                    1
81781c0fed9fe1ad6e8c81fca1e1cb08             1                    1

                                  receita_produtos
product_id
09ff539a621711667c43eba6a3bd8466            1934.0
5eb564652db742ff8f28759cd8d2652a             563.0
e673e90efa65a5409ff4196c038bb5af             519.6
36ba42dd187055e1fbe943b2d11430ca             200.0
8038040ee2a71048d4bdbbdc985b69ab             129.9
81781c0fed9fe1ad6e8c81fca1e1cb08             100.0

In [80]:
df_translation = tabelas["product_category_name_translation"]

print("Dimensões:", df_translation.shape)

print("\nColunas:")
print(df_translation.columns.tolist())

print("\nCategorias únicas:")
print(df_translation["product_category_name"].nunique())

print("\nCategorias em inglês únicas:")
print(df_translation["product_category_name_english"].nunique())

print("\nValores nulos:")
print(df_translation.isna().sum())

print("\nDuplicatas:")
print(df_translation.duplicated().sum())

Dimensões: (71, 2)

Colunas:
['product_category_name', 'product_category_name_english']

Categorias únicas:
71

Categorias em inglês únicas:
71

Valores nulos:
product_category_name            0
product_category_name_english    0
dtype: int64

Duplicatas:
0

In [81]:
categorias_products = set(
    df_products["product_category_name"].dropna().unique()
)

categorias_translation = set(
    df_translation["product_category_name"].unique()
)

categorias_sem_traducao = categorias_products - categorias_translation
categorias_sem_produtos = categorias_translation - categorias_products

print("Categorias não nulas em products:",
      len(categorias_products))

print("Categorias na tabela de tradução:",
      len(categorias_translation))

print("\nCategorias de products sem tradução:",
      len(categorias_sem_traducao))

print(categorias_sem_traducao)

print("\nCategorias traduzidas sem produtos:",
      len(categorias_sem_produtos))

print(categorias_sem_produtos)

Categorias não nulas em products: 73
Categorias na tabela de tradução: 71

Categorias de products sem tradução: 2
{'pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos'}

Categorias traduzidas sem produtos: 0
set()

In [82]:
categorias_sem_traducao = [
    "pc_gamer",
    "portateis_cozinha_e_preparadores_de_alimentos"
]

produtos_sem_traducao = df_products[
    df_products["product_category_name"].isin(categorias_sem_traducao)
][
    ["product_id", "product_category_name"]
]

vendas_sem_traducao = df_items.merge(
    produtos_sem_traducao,
    on="product_id",
    how="inner"
)

print("Produtos nas categorias sem tradução:",
      produtos_sem_traducao["product_id"].nunique())

print("Linhas de venda:",
      len(vendas_sem_traducao))

print("\nResumo por categoria:")
print(
    vendas_sem_traducao
    .groupby("product_category_name")
    .agg(
        produtos=("product_id", "nunique"),
        linhas_venda=("product_id", "size"),
        receita_produtos=("price", "sum")
    )
    .sort_values("receita_produtos", ascending=False)
)

Produtos nas categorias sem tradução: 13
Linhas de venda: 24

Resumo por categoria:
                                               produtos  linhas_venda  \
product_category_name
portateis_cozinha_e_preparadores_de_alimentos        10            15
pc_gamer                                              3             9

                                               receita_produtos
product_category_name
portateis_cozinha_e_preparadores_de_alimentos           3968.53
pc_gamer                                                1545.95

In [83]:
df_sellers = tabelas["olist_sellers_dataset"]

print("Dimensões:", df_sellers.shape)

print("\nColunas:")
print(df_sellers.columns.tolist())

print("\nTipos:")
print(df_sellers.dtypes)

print("\nValores nulos:")
print(df_sellers.isna().sum())

print("\nSellers únicos:")
print(df_sellers["seller_id"].nunique())

print("\nDuplicatas completas:")
print(df_sellers.duplicated().sum())

Dimensões: (3095, 4)

Colunas:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

Tipos:
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

Valores nulos:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Sellers únicos:
3095

Duplicatas completas:
0

In [84]:
sellers_nos_itens = set(df_items["seller_id"].unique())
sellers_na_tabela = set(df_sellers["seller_id"].unique())

sellers_sem_cadastro = sellers_nos_itens - sellers_na_tabela
sellers_sem_vendas = sellers_na_tabela - sellers_nos_itens

print("Sellers presentes em order_items:",
      len(sellers_nos_itens))

print("Sellers presentes em sellers:",
      len(sellers_na_tabela))

print("\nSellers em order_items sem cadastro em sellers:",
      len(sellers_sem_cadastro))

print("Sellers cadastrados sem vendas em order_items:",
      len(sellers_sem_vendas))

Sellers presentes em order_items: 3095
Sellers presentes em sellers: 3095

Sellers em order_items sem cadastro em sellers: 0
Sellers cadastrados sem vendas em order_items: 0

In [85]:
print("Estados dos sellers:")
print(df_sellers["seller_state"].value_counts())

print("\nQuantidade de cidades:")
print(df_sellers["seller_city"].nunique())

print("\nQuantidade de CEPs:")
print(df_sellers["seller_zip_code_prefix"].nunique())

Estados dos sellers:
seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
AC       1
PI       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

Quantidade de cidades:
611

Quantidade de CEPs:
2246

In [86]:
vendas_por_seller = (
    df_items
    .groupby("seller_id")
    .agg(
        linhas_venda=("seller_id", "size"),
        receita_produtos=("price", "sum")
    )
    .reset_index()
)

print("Sellers analisados:", vendas_por_seller["seller_id"].nunique())

print("\nEstatísticas das linhas de venda por seller:")
print(vendas_por_seller["linhas_venda"].describe())

print("\nEstatísticas da receita por seller:")
print(vendas_por_seller["receita_produtos"].describe())

Sellers analisados: 3095

Estatísticas das linhas de venda por seller:
count    3095.000000
mean       36.397415
std       119.193461
min         1.000000
25%         2.000000
50%         8.000000
75%        24.000000
max      2033.000000
Name: linhas_venda, dtype: float64

Estatísticas da receita por seller:
count      3095.000000
mean       4391.484233
std       13921.997192
min           3.500000
25%         208.850000
50%         821.480000
75%        3280.830000
max      229472.630000
Name: receita_produtos, dtype: float64

In [87]:
estrutura_seller_estado = (
    df_sellers
    .merge(
        vendas_por_seller,
        on="seller_id",
        how="left"
    )
    .groupby("seller_state")
    .agg(
        sellers=("seller_id", "nunique"),
        linhas_venda=("linhas_venda", "sum"),
        receita_produtos=("receita_produtos", "sum")
    )
    .sort_values("receita_produtos", ascending=False)
)

print(estrutura_seller_estado)

              sellers  linhas_venda  receita_produtos
seller_state
SP               1849         80342        8753396.21
PR                349          8671        1261887.21
MG                244          8827        1011564.74
RJ                171          4818         843984.22
SC                190          4075         632426.07
RS                129          2199         378559.54
BA                 19           643         285561.56
DF                 30           899          97749.48
PE                  9           448          91493.85
GO                 40           520          66399.21
ES                 23           372          47689.61
MA                  1           405          36408.95
CE                 13            94          20240.64
PB                  6            38          17095.00
MT                  4           145          17070.72
RN                  5            56           9992.60
MS                  5            50           8551.69
RO                  2            14           4762.20
PI                  1            12           2522.00
SE                  2            10           1606.20
PA                  1             8           1238.00
AM                  1             3           1177.00
AC                  1             1            267.00

In [88]:
df_reviews = tabelas["olist_order_reviews_dataset"]

print("Dimensões:", df_reviews.shape)

print("\nColunas:")
print(df_reviews.columns.tolist())

print("\nTipos:")
print(df_reviews.dtypes)

print("\nValores nulos:")
print(df_reviews.isna().sum())

print("\nIDs de pedido únicos:")
print(df_reviews["order_id"].nunique())

print("\nDuplicatas completas:")
print(df_reviews.duplicated().sum())

Dimensões: (99224, 7)

Colunas:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

Tipos:
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

Valores nulos:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

IDs de pedido únicos:
98673

Duplicatas completas:
0

In [89]:
reviews_por_pedido = (
    df_reviews
    .groupby("order_id")
    .size()
)

print("Pedidos com review:", reviews_por_pedido.size)

print("\nDistribuição de reviews por pedido:")
print(reviews_por_pedido.value_counts().sort_index())

print("\nMáximo de reviews para um pedido:",
      reviews_por_pedido.max())

Pedidos com review: 98673

Distribuição de reviews por pedido:
1    98126
2      543
3        4
Name: count, dtype: int64

Máximo de reviews para um pedido: 3

In [90]:
orders_com_review = set(df_reviews["order_id"].unique())
orders_na_tabela = set(df_orders["order_id"].unique())

reviews_sem_pedido = orders_com_review - orders_na_tabela
pedidos_sem_review = orders_na_tabela - orders_com_review

print("Pedidos em reviews:", len(orders_com_review))
print("Pedidos em orders:", len(orders_na_tabela))

print("\nReviews cujo order_id NÃO existe em orders:",
      len(reviews_sem_pedido))

print("Pedidos sem review:",
      len(pedidos_sem_review))

Pedidos em reviews: 98673
Pedidos em orders: 99441

Reviews cujo order_id NÃO existe em orders: 0
Pedidos sem review: 768

In [91]:
print("Distribuição das notas:")
print(df_reviews["review_score"].value_counts().sort_index())

print("\nPercentual das notas:")
print(
    df_reviews["review_score"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

Distribuição das notas:
review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

Percentual das notas:
review_score
1    11.51
2     3.18
3     8.24
4    19.29
5    57.78
Name: proportion, dtype: float64

In [92]:
print("Reviews com título:")
print(df_reviews["review_comment_title"].notna().sum())

print("\nReviews com mensagem:")
print(df_reviews["review_comment_message"].notna().sum())

print("\nReviews sem título E sem mensagem:")
print(
    (
        df_reviews["review_comment_title"].isna()
        & df_reviews["review_comment_message"].isna()
    ).sum()
)

Reviews com título:
11568

Reviews com mensagem:
40977

Reviews sem título E sem mensagem:
56518

In [93]:
print("Reviews totais:", len(df_reviews))

print("review_id únicos:",
      df_reviews["review_id"].nunique())

print("\nDuplicatas de review_id:",
      df_reviews["review_id"].duplicated().sum())

print("\nDuplicatas de (order_id, review_id):",
      df_reviews.duplicated(
          subset=["order_id", "review_id"]
      ).sum())

Reviews totais: 99224
review_id únicos: 98410

Duplicatas de review_id: 814

Duplicatas de (order_id, review_id): 0

In [94]:
reviews_id_repetidos = (
    df_reviews["review_id"]
    .value_counts()
    .loc[lambda x: x > 1]
)

print("Quantidade de review_id repetidos:",
      len(reviews_id_repetidos))

print("\nDistribuição da quantidade de ocorrências:")
print(reviews_id_repetidos.value_counts().sort_index())

print("\nMaior número de ocorrências de um mesmo review_id:",
      reviews_id_repetidos.max())

Quantidade de review_id repetidos: 789

Distribuição da quantidade de ocorrências:
count
2    764
3     25
Name: count, dtype: int64

Maior número de ocorrências de um mesmo review_id: 3

In [95]:
exemplos_review_repetido = (
    df_reviews[
        df_reviews["review_id"].isin(reviews_id_repetidos.index)
    ]
    .sort_values("review_id")
)

print(
    exemplos_review_repetido[
        [
            "review_id",
            "order_id",
            "review_score",
            "review_creation_date"
        ]
    ].head(20).to_string(index=False)
)

                       review_id                         order_id  review_score review_creation_date
00130cbe1f9d422698c812ed8ded1919 dfcdfc43867d1c1381bfaf62d6b9c195             1  2018-03-07 00:00:00
00130cbe1f9d422698c812ed8ded1919 04a28263e085d399c97ae49e0b477efa             1  2018-03-07 00:00:00
0115633a9c298b6a98bcbe4eee75345f 78a4201f58af3463bdab842eea4bc801             5  2017-09-21 00:00:00
0115633a9c298b6a98bcbe4eee75345f 0c9850b2c179c1ef60d2855e2751d1fa             5  2017-09-21 00:00:00
0174caf0ee5964646040cd94e15ac95e f93a732712407c02dce5dd5088d0f47b             1  2018-03-07 00:00:00
0174caf0ee5964646040cd94e15ac95e 74db91e33b4e1fd865356c89a61abf1f             1  2018-03-07 00:00:00
017808d29fd1f942d97e50184dfb4c13 8daaa9e99d60fbba579cc1c3e3bfae01             5  2018-03-02 00:00:00
017808d29fd1f942d97e50184dfb4c13 b1461c8882153b5fe68307c46a506e39             5  2018-03-02 00:00:00
0254bd905dc677a6078990aad3331a36 5bf226cf882c5bf4247f89a97c86f273             1  2017-09-09 00:00:00
0254bd905dc677a6078990aad3331a36 331b367bdd766f3d1cf518777317b5d9             1  2017-09-09 00:00:00
0288d42bef3dfe36930740c9588a570f 33d8795f04dd631f3480d7aaf90da3dc             3  2017-07-29 00:00:00
0288d42bef3dfe36930740c9588a570f f889a5a0b44adc29c5465b99395ac3c1             3  2017-07-29 00:00:00
02aa7f5f75e964e3c7efa59a1f515281 d8e17d5f7dacf0970d316e7c03e741e8             3  2017-07-27 00:00:00
02aa7f5f75e964e3c7efa59a1f515281 db92613c074f00e53066388d48ad7512             3  2017-07-27 00:00:00
034528cb00b6bc981847acafbdf2ae0b e1e8e3bca903de27e9a1c72b5a5795e0             1  2017-05-14 00:00:00
034528cb00b6bc981847acafbdf2ae0b 3d3742a96f24a8fe4e2e57628807e476             1  2017-05-14 00:00:00
03a6a25db577d0689440933055111897 2acfdc5131ff2cf4433e668454c9784c             5  2017-12-15 00:00:00
03a6a25db577d0689440933055111897 3fde8b7313af6b37b84b5c7594d7add0             5  2017-12-15 00:00:00
0467560f511c516ddaa54a60edb0c291 0c995611a99f81268d859184a416f1db             5  2017-02-09 00:00:00
0467560f511c516ddaa54a60edb0c291 55b2e390d5d80ada31ad1b795ebeb087             5  2017-02-09 00:00:00

In [96]:
notas_por_pedido = (
    df_reviews
    .groupby("order_id")["review_score"]
    .nunique()
)

print("Pedidos com mais de uma review:",
      (reviews_por_pedido > 1).sum())

print("\nPedidos com múltiplas reviews e notas diferentes:",
      ((reviews_por_pedido > 1) & (notas_por_pedido > 1)).sum())

print("\nDistribuição da quantidade de notas distintas:")
print(
    notas_por_pedido[reviews_por_pedido > 1]
    .value_counts()
    .sort_index()
)

Pedidos com mais de uma review: 547

Pedidos com múltiplas reviews e notas diferentes: 202

Distribuição da quantidade de notas distintas:
review_score
1    345
2    202
Name: count, dtype: int64

In [97]:
reviews_multiplas = df_reviews[
    df_reviews["order_id"].isin(
        reviews_por_pedido[reviews_por_pedido > 1].index
    )
].copy()

reviews_multiplas["review_creation_date"] = pd.to_datetime(
    reviews_multiplas["review_creation_date"]
)

datas_por_pedido = (
    reviews_multiplas
    .groupby("order_id")["review_creation_date"]
    .agg(
        quantidade_datas="nunique",
        primeira_data="min",
        ultima_data="max"
    )
)

print("Pedidos com múltiplas reviews:",
      len(datas_por_pedido))

print("\nDistribuição da quantidade de datas distintas:")
print(
    datas_por_pedido["quantidade_datas"]
    .value_counts()
    .sort_index()
)

print("\nPedidos com múltiplas reviews em datas diferentes:",
      (datas_por_pedido["quantidade_datas"] > 1).sum())

Pedidos com múltiplas reviews: 547

Distribuição da quantidade de datas distintas:
quantidade_datas
1    155
2    390
3      2
Name: count, dtype: int64

Pedidos com múltiplas reviews em datas diferentes: 392

In [98]:
estrutura_reviews = (
    reviews_multiplas
    .groupby("order_id")
    .agg(
        quantidade_reviews=("review_id", "size"),
        quantidade_notas=("review_score", "nunique"),
        quantidade_datas=("review_creation_date", "nunique")
    )
)

estrutura_reviews["notas_diferentes"] = (
    estrutura_reviews["quantidade_notas"] > 1
)

estrutura_reviews["datas_diferentes"] = (
    estrutura_reviews["quantidade_datas"] > 1
)

estrutura_reviews["estrutura"] = "mesma data + mesma nota"

estrutura_reviews.loc[
    (~estrutura_reviews["datas_diferentes"])
    & (estrutura_reviews["notas_diferentes"]),
    "estrutura"
] = "mesma data + notas diferentes"

estrutura_reviews.loc[
    (estrutura_reviews["datas_diferentes"])
    & (~estrutura_reviews["notas_diferentes"]),
    "estrutura"
] = "datas diferentes + mesma nota"

estrutura_reviews.loc[
    (estrutura_reviews["datas_diferentes"])
    & (estrutura_reviews["notas_diferentes"]),
    "estrutura"
] = "datas diferentes + notas diferentes"

print(
    estrutura_reviews["estrutura"]
    .value_counts()
)

estrutura
datas diferentes + mesma nota          220
datas diferentes + notas diferentes    172
mesma data + mesma nota                125
mesma data + notas diferentes           30
Name: count, dtype: int64

In [99]:
texto_por_pedido = (
    reviews_multiplas
    .assign(
        texto_completo=lambda x: (
            x["review_comment_title"].fillna("")
            + " | "
            + x["review_comment_message"].fillna("")
        ).str.strip()
    )
    .groupby("order_id")["texto_completo"]
    .nunique()
)

print("Pedidos com múltiplas reviews:",
      len(texto_por_pedido))

print("\nDistribuição da quantidade de textos distintos:")
print(
    texto_por_pedido
    .value_counts()
    .sort_index()
)

print("\nPedidos com textos diferentes entre as reviews:",
      (texto_por_pedido > 1).sum())

Pedidos com múltiplas reviews: 547

Distribuição da quantidade de textos distintos:
texto_completo
1    313
2    232
3      2
Name: count, dtype: int64

Pedidos com textos diferentes entre as reviews: 234